// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// AMPscript FUNCTIONS — category: Content (21 entries).

import { INF } from '../constants.js';

export const CONTENT_FUNCTIONS = [
    {
        name: 'AttachFile',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-attach-file.html',
        guideUrl: 'https://ampscript.guide/attachfile/',
        minArgs: 2,
        maxArgs: 8,
        category: 'Content',
        description: 'Includes a file attachment in the outgoing message.',
        params: [
            {
                name: 'fileLocationType',
                description:
                    'The type of location to pull the file from. Accepted values: http, ftp, contentbuilder',
                type: 'string',
                enum: ['http', 'ftp', 'contentbuilder'],
            },
            {
                name: 'fileLocation',
                description:
                    'The location to pull the file from. This parameter can contain a maximum of 2088 characters. If you specify http for the first parameter, this parameter must contain a URL. If you specify ftp for the first parameter, this parameter must contain the name of a file in the Import folder of your Enhanced FTP site. If you specify contentbuilder for the first parameter, this parameter must contain the external key of the file to attach.',
                type: 'string',
            },
            {
                name: 'attachmentFileName',
                description:
                    "The name assigned to a file when it's attached to an email message. If you don't specify a new name, the function uses the original file name. If you specify http for the first parameter and don't provide a value for this parameter, the function uses the Content-Disposition information from the HTTP header. If the server providing the file doesn't provide Content-Disposition information, the function uses an auto-generated value.",
                type: 'string',
                optional: true,
            },
            {
                name: 'viewOnWeb',
                description:
                    'If `true` or `1`, a link to the file is included when a recipient selects the "View as a Web Page" link in the email. If `false` or `0`, the link is omitted. You can only use this parameter if the value of the first parameter is `http`.',
                type: 'boolean',
                optional: true,
            },
            {
                name: 'viewOnWebUrl',
                description:
                    'The URL to use when including a link to the file in the "View as a Web Page" context. If the value of `viewOnWeb` is true, you must provide a value for this parameter. You can only use this parameter if the value of the first parameter is `http`.',
                type: 'string',
                optional: true,
            },
            {
                name: 'viewOnWebFileName',
                description:
                    'The file name to use when including a link to the file in the "View as a Web Page" context. You can only use this parameter if the value of the first parameter is `http`.',
                type: 'string',
                optional: true,
            },
            {
                name: 'viewOnWebDuration',
                description:
                    'The number of days the link appears in the "View as a Web Page" context. You can only use this parameter if the value of the first parameter is `http`.',
                type: 'number',
                optional: true,
            },
            {
                name: 'contentDispositionAttachment',
                description:
                    'If `true` or `1`, the function changes the value of the `content-disposition` header for the attachment to `attachment`. If `false` or `0`, the value of this header is set to `inline`.',
                type: 'boolean',
                optional: true,
            },
        ],
        returnType: 'void',
        returnDescription: 'No value is returned; the file is attached to the outgoing email.',
        syntax: 'AttachFile(fileLocationType, fileLocation, attachmentFileName, viewOnWeb, viewOnWebUrl, viewOnWebFileName, viewOnWebDuration, contentDispositionAttachment)',
        example: "%%=AttachFile('http', 'https://example.com/catalog.pdf', 'Catalog.pdf')=%%",
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
        officialDocsNote:
            'AttachFile targets the outgoing email at send time; it has no working invocation on a CloudPage. Every reached call — contentbuilder key, http URL, and the two-argument minimum form — aborted the page with HTTP 422 and no partial output, on the child BU and again on the parent BU. The abort only happens when the call is actually reached: gating it behind an unmatched query-string branch leaves the page at HTTP 200, so the failure is a runtime abort of the reached call rather than a compile-time rejection. An email-context render on the child BU sharpened the cause: the Email Preview API recognises and evaluates the function and fails with a precise message that the EMAIL_ATTACHMENTS business rule must be turned on before AttachFile can be used, so the block is an account-level provisioning gate rather than a broken function.',
    },
    {
        name: 'BarcodeURL',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-barcode-url.html',
        guideUrl: 'https://ampscript.guide/barcodeurl/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/barcodeurl/',
        minArgs: 4,
        maxArgs: 9,
        category: 'Content',
        description:
            'Generates a URL that renders a barcode image from the given value, symbology, width, and height, plus optional formatting. An empty value aborts the page instead of returning an empty result.',
        params: [
            {
                name: 'valueToConvert',
                description: 'Data to convert into a barcode',
                type: 'string',
            },
            {
                name: 'barcodeType',
                description: 'Type of barcode to generate',
                type: 'string',
                enum: [
                    'codabar',
                    'code11',
                    'code128auto',
                    'code128a',
                    'code128b',
                    'code128c',
                    'code39',
                    'code39ext',
                    'code93',
                    'code93ext',
                    'datamatrix',
                    'ean13',
                    'ean8',
                    'industr25',
                    'interl25',
                    'msi',
                    'pdf417',
                    'upca',
                    'upce',
                ],
            },
            { name: 'width', description: 'Barcode image width in pixels', type: 'number' },
            { name: 'height', description: 'Barcode image height in pixels', type: 'number' },
            {
                name: 'checksumValue',
                description: 'Checksum value for barcode',
                type: 'string',
                optional: true,
            },
            {
                name: 'showText',
                description:
                    "If `true` or `1`, the function includes the text of `valueToConvert` under the barcode. If `false` or `0`, the function doesn't include the text of `valueToConvert` under the barcode. The default value is `false`.",
                type: 'boolean',
                optional: true,
            },
            {
                name: 'altText',
                description: 'Alternate text to display under the barcode if `showText` is `false`',
                type: 'string',
                optional: true,
            },
            {
                name: 'rotation',
                description: 'Orientation of barcode in degrees',
                type: 'number',
                enum: [0, 90, 180, 270],
                optional: true,
            },
            {
                name: 'transparentBG',
                description:
                    'If `true` or `1`, the barcode includes a transparent background. Otherwise, the background is white. The default value is `false`.',
                type: 'boolean',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'A URL that renders the requested barcode image.',
        syntax: 'BarcodeURL(valueToConvert, barcodeType, width, height, checksumValue, showText, altText, rotation, transparentBG)',
        example: "<img src=\"%%=BarcodeURL('12345678901', 'code128auto', 150, 50)=%%\">",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'BeginImpressionRegion',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-begin-impression-region.html',
        guideUrl: 'https://ampscript.guide/beginimpressionregion/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/beginimpressionregion/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'Content',
        description:
            'Marks the start of an impression tracking region. The region name must be a literal — a variable argument aborts the page.',
        params: [{ name: 'regionName', description: 'Impression region name', type: 'string' }],
        returnType: 'void',
        returnDescription: 'No value is returned; it marks the start of an impression region.',
        syntax: 'BeginImpressionRegion(regionName)',
        example: "BeginImpressionRegion('Region A')",
    },
    {
        name: 'BuildOptionList',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-build-option-list.html',
        guideUrl: 'https://ampscript.guide/buildoptionlist/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/buildoptionlist/',
        minArgs: 3,
        maxArgs: INF,
        category: 'Content',
        description:
            'Builds HTML <option> elements from supplied value/text pairs for use in a <select> dropdown, marking the pair whose value matches the default selection as selected.',
        params: [
            {
                name: 'defaultSelection',
                mcnSince: null,
                mcnNotes: null,
                description: 'The option that is selected by default',
                type: 'string|number',
            },
            {
                name: 'option1Value',
                description:
                    'An identifier for the first option. The function sets the `value` parameter in the `<option>` tag to this value.',
                type: 'string',
            },
            {
                name: 'option1Text',
                description: 'The display text for the option tag.',
                type: 'string',
            },
            {
                name: 'optionValueN',
                description:
                    'An identifier for an additional option. The function sets the `value` parameter in the `<option>` tag to this value.',
                type: 'string',
                optional: true,
            },
            {
                name: 'optionTextN',
                description: 'The display text for the additional option tag.',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'An HTML string of option elements built from the supplied values.',
        repeat: [{ startIndex: 1, groupSize: 2, minGroups: 1 }],
        syntax: 'BuildOptionList(defaultSelection, option1Value, option1Text[, optionValueN, optionTextN, ...])',
        example:
            '%%[\n' +
            'set @DefaultOption = 2\n' +
            'set @OptionList = BuildOptionList(@DefaultOption, "1", "Option A", "2", "Option B", "3", "Option C")\n' +
            ']%%\n' +
            '<p>Choose an option:</p>\n' +
            '<select name="choice">\n%%=v(@OptionList)=%%\n</select>',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'BuildRowsetFromJSON',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'jsonPath',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-build-rowset-from-json.html',
        guideUrl: 'https://ampscript.guide/buildrowsetfromjson/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/buildrowsetfromjson/',
        minArgs: 3,
        maxArgs: 3,
        category: 'Content',
        description: 'Parses a JSON string and returns a rowset.',
        params: [
            {
                name: 'jsonData',
                description: 'The JSON data that you want to parse',
                type: 'string',
            },
            {
                name: 'jsonPathExpression',
                mcnSince: null,
                mcnNotes: null,
                description: 'The JSONPath expression that parses the source data',
                type: 'string',
            },
            {
                name: 'returnEmptyOnError',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Pass 1 or true to get an empty rowset when the payload or path cannot be parsed; 0 or false makes the same input abort the page',
                type: 'boolean|number',
            },
        ],
        returnType: 'rowset',
        returnDescription:
            'A rowset built from the matched JSON nodes. A path that matches nothing yields a rowset with zero rows rather than an error.',
        syntax: 'BuildRowsetFromJSON(jsonData, jsonPathExpression, returnEmptyOnError)',
        example: "%%[ SET @rows = BuildRowsetFromJSON(@json, '$.items[*]', 1) ]%%",
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official syntax section states that a false third argument yields an empty rowset and a true one raises an exception; runtime on the child BU (CloudPage GET) does the opposite. Malformed JSON with 1 rendered a rowset of zero rows, while the identical payload with 0 aborted the page with HTTP 422. The same page also proved that an unparsable payload, an unset variable, an empty string, [] and a path matching nothing all yield zero rows when 1 is passed. Note the official Errors section already describes the runtime ordering, so the page contradicts itself.',
    },
    {
        name: 'BuildRowSetFromString',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-build-rowset-from-string.html',
        guideUrl: 'https://ampscript.guide/buildrowsetfromstring/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/buildrowsetfromstring/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Content',
        description: 'Splits a delimited string into a single-column rowset.',
        params: [
            {
                name: 'sourceData',
                description: 'A string that contains the data to load into a rowset',
                type: 'string',
            },
            {
                name: 'delimiter',
                description:
                    'The separator to split on; it may be several characters long, and an empty separator leaves the input as a single row',
                type: 'string',
            },
        ],
        returnType: 'rowset',
        returnDescription:
            'A rowset where each row holds one delimited segment of the input string. The single column has no name, so read it with Field(row, 1). An empty or unset input gives zero rows.',
        syntax: 'BuildRowSetFromString(sourceData, delimiter)',
        example: "%%=BuildRowSetFromString('a,b,c', ',')=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'BuildRowSetFromXML',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-build-rowset-from-xml.html',
        guideUrl: 'https://ampscript.guide/buildrowsetfromxml/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/buildrowsetfromxml/',
        minArgs: 3,
        maxArgs: 3,
        category: 'Content',
        description: 'Parses an XML string using an XPath expression and returns a rowset.',
        params: [
            { name: 'xmlData', description: 'The XML data that you want to parse', type: 'string' },
            {
                name: 'xpathExpression',
                description: 'The XPath expression that parses the source data',
                type: 'string',
            },
            {
                name: 'returnEmptyOnError',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Pass 1 or true to get an empty rowset when the payload or path cannot be parsed; 0 or false makes the same input abort the page',
                type: 'boolean|number',
            },
        ],
        returnType: 'rowset',
        returnDescription:
            'A rowset built from the matched XML nodes, with a Value column, an Xml column holding the inner markup, and one <attribute>_att column per attribute seen on any matched node. An XPath that matches nothing yields zero rows rather than an error.',
        syntax: 'BuildRowSetFromXML(xmlData, xpathExpression, returnEmptyOnError)',
        example: "%%[ SET @rows = BuildRowSetFromXML(@xml, '/root/item', 1) ]%%",
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official syntax section states that a false third argument yields an empty rowset and a true one raises an exception; runtime on the child BU (CloudPage GET) behaves the other way round. Unclosed XML parsed with 1 rendered a rowset of zero rows, whereas the identical payload with 0 aborted the page with HTTP 422. An empty string, an unset variable, an empty root element and an XPath matching nothing likewise gave zero rows under 1.',
    },
    {
        name: 'ContentArea',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-area.html',
        guideUrl: 'https://ampscript.guide/contentarea/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentarea/',
        minArgs: 1,
        maxArgs: 5,
        category: 'Content',
        description: 'Inserts a classic content area by its numeric ID.',
        params: [
            {
                name: 'contentAreaId',
                mcnSince: null,
                mcnNotes: null,
                description: 'The ID of the content area to retrieve',
                type: 'number|string',
            },
            {
                name: 'impressionRegionName',
                mcnSince: null,
                mcnNotes: null,
                description: 'The name of the impression region to associate with the content area',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorOnMissingContentArea',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "Determines whether the function returns an error when the system can't locate the specified content area or returns an invalid content area. A value of true returns an error. Defaults to true.",
                type: 'boolean',
                optional: true,
                default: true,
            },
            {
                name: 'errorMessage',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Default content to return if an error occurs. This value is emitted literally - any AMPscript it contains is not evaluated.',
                type: 'string',
                optional: true,
            },
            {
                name: 'statusCode',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'An output variable that contains the exit code of the function. A value of 0 indicates the function found the content area and successfully rendered the content. A value of -1 indicates either no content or an invalid content area.',
                type: 'number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The rendered HTML of the referenced content area.',
        syntax: 'ContentArea(contentAreaId[, impressionRegionName, errorOnMissingContentArea, errorMessage, statusCode])',
        example: '%%=ContentArea(12345)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        deprecated: true,
        deprecatedReplacement: 'ContentBlockByID',
        deprecatedReason:
            'ContentArea references classic content areas, which are no longer supported. Use Content Builder content blocks instead.',
    },
    {
        name: 'ContentAreaByName',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-area-by-name.html',
        guideUrl: 'https://ampscript.guide/contentareabyname/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentareabyname/',
        minArgs: 1,
        maxArgs: 5,
        category: 'Content',
        description: 'Inserts a classic content area by its folder path and name.',
        params: [
            {
                name: 'contentAreaName',
                description: 'The name of the content area to retrieve',
                type: 'string',
            },
            {
                name: 'impressionRegionName',
                mcnSince: null,
                mcnNotes: null,
                description: 'The name of the impression region to associate with the content area',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorOnMissingContentArea',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "Determines whether the function returns an error when the system can't locate the specified content area or returns an invalid content area. A value of true returns an error. Defaults to true.",
                type: 'boolean',
                optional: true,
                default: true,
            },
            {
                name: 'errorMessage',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Default content to return if an error occurs. This value is emitted literally - any AMPscript it contains is not evaluated.',
                type: 'string',
                optional: true,
            },
            {
                name: 'statusCode',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'An output variable that contains the exit code of the function. A value of 0 indicates the function found the content area and successfully rendered the content. A value of -1 indicates either no content or an invalid content area.',
                type: 'number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The rendered HTML of the named content area.',
        syntax: 'ContentAreaByName(contentAreaName[, impressionRegionName, errorOnMissingContentArea, errorMessage, statusCode])',
        example: String.raw`%%=ContentAreaByName('My Folder\My Content')=%%`,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        deprecated: true,
        deprecatedReplacement: 'ContentBlockByName',
        deprecatedReason:
            'ContentAreaByName references classic content areas, which are no longer supported. Use Content Builder content blocks instead.',
    },
    {
        name: 'ContentBlockByID',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-block-by-id.html',
        guideUrl: 'https://ampscript.guide/contentblockbyid/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentblockbyid/',
        minArgs: 1,
        maxArgs: 5,
        category: 'Content',
        description: 'Retrieves and renders a Content Builder content block by its numeric ID.',
        params: [
            {
                name: 'contentBlockId',
                description: 'The ID of the content block to retrieve',
                type: 'number|string',
            },
            {
                name: 'impressionRegionName',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'The name of the impression region to associate with the content block',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorOnMissingContentBlock',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "If true, the function returns an error if the content block can't be found. If false, the function doesn't return an error. The default value is true",
                type: 'boolean',
                optional: true,
                default: true,
            },
            {
                name: 'errorMessage',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Default content to return if an error occurs. This value is emitted literally - any AMPscript it contains is not evaluated.',
                type: 'string',
                optional: true,
            },
            {
                name: 'statusCode',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'The exit code of the function. A value of 0 indicates the function found the content block and successfully rendered the content. A value of -1 indicates either no content or an invalid content block.',
                type: 'number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The rendered HTML of the content block identified by ID.',
        syntax: 'ContentBlockByID(contentBlockId[, impressionRegionName, errorOnMissingContentBlock, errorMessage, statusCode])',
        example: '%%=ContentBlockByID(12345)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'ContentBlockByKey',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'getContentBlock',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-block-by-key.html',
        guideUrl: 'https://ampscript.guide/contentblockbykey/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentblockbykey/',
        minArgs: 1,
        maxArgs: 5,
        category: 'Content',
        description: 'Retrieves and renders a Content Builder content block by its customer key.',
        params: [
            {
                name: 'contentBlockKey',
                description: 'The key of the content block to retrieve',
                type: 'string',
            },
            {
                name: 'impressionRegionName',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'The name of the impression region to associate with the content block',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorOnMissingContentBlock',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "If true, the function returns an error if the content block can't be found. If false, the function doesn't return an error. The default value is true",
                type: 'boolean',
                optional: true,
                default: true,
            },
            {
                name: 'errorMessage',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Default content to return if an error occurs. This value is emitted literally - any AMPscript it contains is not evaluated.',
                type: 'string',
                optional: true,
            },
            {
                name: 'statusCode',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'The exit code of the function. A value of 0 indicates the function found the content block and successfully rendered the content. A value of -1 indicates either no content or an invalid content block.',
                type: 'number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The rendered HTML of the content block identified by customer key.',
        syntax: 'ContentBlockByKey(contentBlockKey[, impressionRegionName, errorOnMissingContentBlock, errorMessage, statusCode])',
        example: "%%=ContentBlockByKey('welcome-header')=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'ContentBlockByName',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-block-by-name.html',
        guideUrl: 'https://ampscript.guide/contentblockbyname/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentblockbyname/',
        minArgs: 1,
        maxArgs: 5,
        category: 'Content',
        description:
            'Retrieves and renders a Content Builder content block by its folder path and name.',
        params: [
            {
                name: 'contentBlockName',
                description: 'The full path of the content block to retrieve',
                type: 'string',
            },
            {
                name: 'impressionRegionName',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'The name of the impression region to associate with the content block',
                type: 'string',
                optional: true,
            },
            {
                name: 'errorOnMissingContentBlock',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "If true, the function returns an error if the content block can't be found. If false, the function doesn't return an error. The default value is true",
                type: 'boolean',
                optional: true,
                default: true,
            },
            {
                name: 'errorMessage',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Default content to return if an error occurs. This value is emitted literally - any AMPscript it contains is not evaluated.',
                type: 'string',
                optional: true,
            },
            {
                name: 'statusCode',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'The exit code of the function. A value of 0 indicates the function found the content block and successfully rendered the content. A value of -1 indicates either no content or an invalid content block.',
                type: 'number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The rendered HTML of the content block identified by name or path.',
        syntax: 'ContentBlockByName(contentBlockName[, impressionRegionName, errorOnMissingContentBlock, errorMessage, statusCode])',
        example: String.raw`%%=ContentBlockByName('My Folder\Welcome Header')=%%`,
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'ContentImageByID',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-image-by-id.html',
        guideUrl: 'https://ampscript.guide/contentimagebyid/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentimagebyid/',
        minArgs: 1,
        maxArgs: 2,
        category: 'Content',
        description:
            'Returns an HTML img tag for a Content Builder image asset by its numeric ID. A missing image with no fallback aborts the page.',
        params: [
            {
                name: 'id',
                description: 'The ID of an image in Content Builder',
                type: 'number|string',
            },
            {
                name: 'defaultImageExternalId',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "The ID of a fallback image in Content Builder. The function uses this image if it can't find the image that you specified in the first parameter",
                type: 'number|string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'An HTML img tag for the referenced image, with title, alt, border and thid attributes.',
        syntax: 'ContentImageByID(id[, defaultImageExternalId])',
        example: '%%=ContentImageByID(12345)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'ContentImageByKey',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-image-by-key.html',
        guideUrl: 'https://ampscript.guide/contentimagebykey/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/contentimagebykey/',
        minArgs: 1,
        maxArgs: 2,
        category: 'Content',
        description:
            'Returns an HTML img tag for a Content Builder image asset by its customer key. A missing image with no fallback aborts the page.',
        params: [
            {
                name: 'imageExternalKey',
                description: 'External key of the image asset',
                type: 'string',
            },
            {
                name: 'defaultImageExternalKey',
                mcnSince: null,
                mcnNotes: null,
                description: 'External key of the fallback image asset',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'An HTML img tag for the referenced image, with title, alt, border and thid attributes.',
        syntax: 'ContentImageByKey(imageExternalKey[, defaultImageExternalKey])',
        example: "%%=ContentImageByKey('hero-image')=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'EndImpressionRegion',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-end-impression-region.html',
        guideUrl: 'https://ampscript.guide/endimpressionregion/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/endimpressionregion/',
        minArgs: 0,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'Content',
        description: 'Marks the end of an impression tracking region.',
        params: [
            {
                name: 'endAllRegions',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Whether to end all open impression regions. A truthy value ends every open region; the default ends only the most recent one.',
                type: 'string|boolean|number',
                optional: true,
            },
        ],
        returnType: 'void',
        returnDescription: 'No value is returned; it marks the end of an impression region.',
        syntax: 'EndImpressionRegion([endAllRegions])',
        example: 'EndImpressionRegion(0)',
    },
    {
        name: 'GetPortfolioItem',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-get-portfolio-item.html',
        guideUrl: 'https://ampscript.guide/getportfolioitem/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Content',
        description: 'Retrieves metadata for a classic portfolio item.',
        params: [
            {
                name: 'itemExternalKey',
                description: 'External key of the portfolio item',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription: 'The content of the requested Portfolio item.',
        syntax: 'GetPortfolioItem(itemExternalKey)',
        example: "%%=GetPortfolioItem('my-portfolio-key')=%%",
        isConfirmed: true,
        nonFunctionalAtRuntime: true,
        officialDocsNote:
            'Classic Portfolio is retired on this tenant, so no Portfolio item exists to retrieve. A reached call with an external key that does not resolve aborted the page with HTTP 422 and no partial output, on both the child BU and the parent BU; the same call gated behind an unmatched query-string branch left the page at HTTP 200, confirming a runtime abort of the reached call. No valid key could be sourced because Portfolio asset creation and applications were retired, so the documented success path could not be exercised here.',
    },
    {
        name: 'Image',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-image.html',
        guideUrl: 'https://ampscript.guide/image/',
        minArgs: 1,
        maxArgs: 2,
        category: 'Content',
        description:
            'Returns an HTML img tag for the Portfolio image matching the specified external key.',
        params: [
            {
                name: 'imageExternalKey',
                mcnSince: null,
                mcnNotes: null,
                description: 'External key of an image in your Portfolio',
                type: 'string',
            },
            {
                name: 'defaultImageExternalKey',
                mcnSince: null,
                mcnNotes: null,
                description: 'External key of a fallback image used if the primary is not found',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'An HTML img tag for the referenced image.',
        syntax: 'Image(imageExternalKey[, defaultImageExternalKey])',
        example: "%%=Image('CorpLogo', 'DefaultImage')=%%",
        isConfirmed: true,
        nonFunctionalAtRuntime: true,
        deprecated: true,
        deprecatedReason:
            'The classic Portfolio / Classic Content area this function reads from was retired in April 2023, so no image assets exist for it to reference on any current tenant, and every invocation aborts the page at runtime. Use ContentImageByKey or ContentImageByID against Content Builder image assets instead.',
        officialDocsNote:
            'No working invocation was found on either the child BU or the parent BU. Image resolves images from the legacy Portfolio, whose creation and applications have been retired; no Portfolio assets exist on either BU to reference. Every attempt aborted the CloudPage with HTTP 422 and no output: a literal URL, a Content Builder asset external key, and a plausible Portfolio-style key were all tried on the child BU, and a Portfolio-style key on the parent BU. Use ContentImageByKey or ContentImageByID against Content Builder image assets instead.',
    },
    {
        name: 'LiveContentMicrositeURL',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-live-content-microsite-url.html',
        guideUrl: 'https://ampscript.guide/livecontentmicrositeurl/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Content',
        description: 'Generates a URL to a microsite page that serves live, dynamic content.',
        isConfirmed: true,
        nonFunctionalAtRuntime: true,
        deprecated: true,
        deprecatedReason:
            'Live Offers (Live Content) was removed from Marketing Cloud in 2019 and the Classic Microsites this URL points at were retired in June 2022, so there is no provisionable modern equivalent and every invocation aborts the page at runtime.',
        officialDocsNote:
            "Attempted on both the child BU and the parent BU. Every invocation shape aborted the CloudPage with HTTP 200 lost to a 422 page abort: the documented-valid LiveContentMicrositeURL('coupon','MyCoupon'), an unknown content type, and an empty external key all failed identically. The function resolves a Live Offers (Live Content) coupon by external key, and no such Live Content asset is provisioned on either BU, so no working invocation could be produced. Left blocked pending a tenant with a real Live Offers coupon.",
        params: [
            {
                name: 'contentType',
                description:
                    'The type of content to generate a URL for. Accepted values: microsite, landingpage',
                type: 'string',
                enum: ['coupon'],
            },
            {
                name: 'externalKey',
                description: 'The external key of the live content',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription: 'A URL to the referenced live content microsite.',
        syntax: 'LiveContentMicrositeURL(contentType, externalKey)',
        example: '%%=LiveContentMicrositeURL("coupon", "50percent")=%%',
    },
    {
        name: 'TransformXML',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-transform-xml.html',
        guideUrl: 'https://ampscript.guide/transformxml/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/transformxml/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Content',
        description: 'Transforms an XML document using an XSLT stylesheet.',
        isConfirmed: true,
        params: [
            { name: 'xmlDocument', description: 'XML document string', type: 'string' },
            { name: 'xslDocument', description: 'XSLT stylesheet string', type: 'string' },
        ],
        returnType: 'string',
        returnDescription: 'The result of applying the XSL transform to the XML document.',
        syntax: 'TransformXML(xmlDocument, xslDocument)',
        example: '%%=TransformXML(@xml, @xsl)=%%',
    },
    {
        name: 'TreatAsContent',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-treat-as-content.html',
        guideUrl: 'https://ampscript.guide/treatascontent/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/treatascontent/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'Content',
        description:
            'Evaluates a string as AMPscript content, rendering any embedded AMPscript expressions, and returns the rendered string. Plain text and the empty string pass through unchanged.',
        params: [
            {
                name: 'stringToReturn',
                mcnSince: null,
                mcnNotes: null,
                description: 'String containing AMPscript to evaluate',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription: 'The supplied string rendered as AMPscript content.',
        syntax: 'TreatAsContent(stringToReturn)',
        example: '%%=TreatAsContent(@dynamicContent)=%%',
    },
    {
        name: 'TreatAsContentArea',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-treat-as-content-area.html',
        guideUrl: 'https://ampscript.guide/treatascontentarea/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/treatascontentarea/',
        minArgs: 2,
        maxArgs: 3,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'Content',
        description:
            'Stores a content string under a key for the duration of a send and renders it, evaluating any embedded AMPscript. An optional third argument names an impression region.',
        params: [
            { name: 'contentKey', description: 'Content area key identifier', type: 'string' },
            { name: 'contentValue', description: 'HTML/AMPscript content', type: 'string' },
            {
                name: 'impressionRegion',
                mcnSince: null,
                mcnNotes: null,
                description: 'Impression region name',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The supplied value rendered as a content area.',
        syntax: 'TreatAsContentArea(contentKey, contentValue[, impressionRegion])',
        example: "%%=TreatAsContentArea('region-key', @content)=%%",
    },
];
