// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// AMPscript FUNCTIONS — category: HTTP (5 entries).

import { INF } from '../constants.js';

export const HTTP_FUNCTIONS = [
    {
        name: 'HTTPGet',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        isConfirmed: true,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-get.html',
        guideUrl: 'https://ampscript.guide/httpget/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/httpget/',
        minArgs: 1,
        maxArgs: 4,
        category: 'HTTP',
        description: 'Performs an HTTP GET request and returns the response body.',
        params: [
            {
                name: 'httpGetUrl',
                description: 'The URL to perform the HTTP GET operation on',
                type: 'string',
            },
            {
                name: 'continueOnError',
                mcnSince: null,
                mcnNotes: null,
                description: 'If true, ignore errors encountered during the GET operation',
                type: 'boolean',
                optional: true,
            },
            {
                name: 'emptyContentHandling',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'How empty content is handled: 0 allows empty content, 1 returns an error, 2 skips the subscriber in a send',
                type: 'number',
                optional: true,
            },
            {
                name: 'status',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Output variable that receives the function status: 0 success, -1 not found, -2 HTTP request error, -3 empty content',
                type: 'number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The body of the HTTP response as a string.',
        syntax: 'HTTPGet(httpGetUrl[, continueOnError, emptyContentHandling, status])',
        example: "%%=HTTPGet('https://example.com/api')=%%",
    },
    {
        name: 'HTTPPost',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-post.html',
        guideUrl: 'https://ampscript.guide/httppost/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/httppost/',
        minArgs: 3,
        maxArgs: INF,
        category: 'HTTP',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference labels the fourth argument as an output parameter holding the "status" of the request, but on a live Engagement CloudPage (child BU) that variable receives the response BODY, not the status. The HTTP status code is the function return value. A non-2xx response (proven with a 404) and an empty URL both abort the whole page rather than returning the status, so a failing status can never be read from the return value.',
        description:
            'Performs an HTTP POST request and returns the HTTP status code. The response body is written to the optional output variable.',
        params: [
            {
                name: 'urlEndpoint',
                description: 'The URL to post the specified content to',
                type: 'string',
            },
            {
                name: 'contentTypeHeader',
                description: 'The content-type header to use in the POST request',
                type: 'string',
            },
            {
                name: 'contentToPost',
                description: 'The content to send to the specified URL in the POST request',
                type: 'string',
            },
            {
                name: 'response',
                mcnSince: null,
                mcnNotes: null,
                description: 'Output variable that receives the response body',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerName1',
                description: 'The name of an additional header to include in the request',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerValue1',
                description: 'The value of an additional header to include in the request',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerNameN',
                description: 'The name of a further additional header',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerValueN',
                description: 'The value of a further additional header',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'number',
        returnDescription: 'The HTTP status code of the POST request.',
        repeat: [{ startIndex: 4, groupSize: 2, minGroups: 0 }],
        syntax: 'HTTPPost(urlEndpoint, contentTypeHeader, contentToPost[, @response, headerName1, headerValue1, headerNameN, headerValueN, ...])',
        example:
            "%%=HTTPPost('https://example.com/api', 'application/json', @payload, @response)=%%",
    },
    {
        name: 'HTTPPost2',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-post2.html',
        guideUrl: 'https://ampscript.guide/httppost2/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/httppost2/',
        minArgs: 3,
        maxArgs: INF,
        category: 'HTTP',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference labels the fifth argument (response) as storing the "status" of the request, but on a live Engagement CloudPage (child BU) it receives the response BODY and the sixth argument (responseRowSet) receives the response HEADERS as a rowset (11 header rows observed). The HTTP status code is the function return value. The boolean exceptionOnError flag is accepted at position four.',
        description:
            'Performs an HTTP POST and returns the HTTP status code. The response body and the response headers (as a rowset) are written to optional output variables.',
        params: [
            { name: 'url', description: 'Request URL', type: 'string' },
            { name: 'contentType', description: 'Content-Type header', type: 'string' },
            { name: 'contentToPost', description: 'Request body', type: 'string' },
            {
                name: 'exceptionOnError',
                description:
                    'If `true`, raise an exception when the request fails; if `false`, continue after an error',
                type: 'boolean',
                optional: true,
            },
            {
                name: 'response',
                description: 'Output variable for the response body',
                type: 'string',
                optional: true,
            },
            {
                name: 'responseRowSet',
                mcnSince: null,
                mcnNotes: null,
                description: 'Output variable for the response headers, returned as a rowset',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerName1',
                description: 'First request header name',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerValue1',
                description: 'First request header value',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerNameN',
                description: 'Additional request header name',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerValueN',
                description: 'Additional request header value',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'number',
        returnDescription: 'The HTTP status code of the POST request.',
        repeat: [{ startIndex: 6, groupSize: 2, minGroups: 0 }],
        syntax: 'HTTPPost2(url, contentType, contentToPost[, exceptionOnError, @response, @responseRowSet, headerName1, headerValue1, headerNameN, headerValueN, ...])',
        example:
            "%%=HTTPPost2('https://example.com/api', 'application/json', @payload, true, @response, @responseRows)=%%",
    },
    {
        name: 'HTTPPostWithRetry',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-post-with-retry.html',
        guideUrl: 'https://ampscript.guide/httppostwithretry/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/httppostwithretry/',
        minArgs: 3,
        maxArgs: INF,
        category: 'HTTP',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference labels the responseStatus argument as storing the "status" of the request, but on a live Engagement CloudPage (child BU) it receives the response BODY and responseContentRowset receives the response HEADERS as a rowset (11 header rows observed). The HTTP status code is the function return value. The numRetries, reschedule and returnExceptionOnError arguments are all accepted at runtime; retry-on-failure is documented but was not forced here because a transient failure could not be induced safely against the echo endpoint.',
        description:
            'Posts content to the specified URL with automatic retry logic on failure, and returns the HTTP status code. Similar to HTTPPost2 but adds configurable retries and rescheduling; the response body and headers (as a rowset) are written to optional output variables.',
        params: [
            { name: 'urlEndpoint', description: 'The URL to send the content to', type: 'string' },
            {
                name: 'contentTypeHeader',
                description: 'The content-type header to use in the POST request',
                type: 'string',
            },
            {
                name: 'content',
                description: 'The content to send to the specified URL in the POST request',
                type: 'string',
            },
            {
                name: 'numRetries',
                description: 'The number of times the request can be retried',
                type: 'number',
                optional: true,
                default: 3,
            },
            {
                name: 'reschedule',
                description:
                    'Whether the request is rescheduled (retried after 15 minutes) if it still fails after all retries',
                type: 'boolean',
                optional: true,
                default: false,
            },
            {
                name: 'returnExceptionOnError',
                description:
                    'If true, raise an exception on error; if false, continue after an error',
                type: 'boolean',
                optional: true,
            },
            {
                name: 'responseStatus',
                description: 'An AMPscript variable that receives the response body',
                type: 'string',
                optional: true,
            },
            {
                name: 'responseContentRowset',
                description: 'An AMPscript variable that stores the response content as a rowset',
                type: 'rowset',
                optional: true,
            },
            {
                name: 'headerName1',
                description: 'The name of an additional header to include in the request',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerValue1',
                description: 'The value of an additional header to include in the request',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerNameN',
                description: 'The name of a further additional header',
                type: 'string',
                optional: true,
            },
            {
                name: 'headerValueN',
                description: 'The value of a further additional header',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'number',
        returnDescription: 'The HTTP status code of the POST request.',
        repeat: [{ startIndex: 8, groupSize: 2, minGroups: 0 }],
        syntax: 'HTTPPostWithRetry(urlEndpoint, contentTypeHeader, content[, numRetries, reschedule, returnExceptionOnError, @responseStatus, @responseContentRowset, headerName1, headerValue1, headerNameN, headerValueN, ...])',
        example: "%%=HTTPPostWithRetry('https://example.com/api', 'application/json', @payload)=%%",
    },
    {
        name: 'HTTPRequestHeader',
        supportedInCloudPage: true,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Runtime-verified on a live Marketing Cloud Engagement CloudPage (child BU). The official reference states this function can only retrieve the standard HTTP headers listed in RFC 7231, but at runtime it also returns the value of a non-standard custom request header: a request sent with an X-Amp-Probe header returned that exact value, so the RFC 7231 restriction is not enforced when reading headers. A header that is absent from the request (for example Referer when none was sent) returns the empty string, matching the documented note. Email/send-context finding: rendered through the Email Preview API against a seeded sendable row, an isolated HTTPRequestHeader("User-Agent") was rejected with HTTP 400 errorcode 10004 ("HTTPRequestHeader Function is not valid in content. This function is only allowed in content with an HTTP context."). So it works only where an inbound HTTP request exists (CloudPages / landing pages) and cannot be used inside a sendable email, which fits its purpose since request headers are a request-time value absent at send time.',
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-request-header.html',
        guideUrl: 'https://ampscript.guide/httprequestheader/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/httprequestheader/',
        minArgs: 1,
        maxArgs: 1,
        category: 'HTTP',
        description:
            'Returns the value of a specified HTTP request header from the inbound request.',
        params: [
            {
                name: 'headerToRetrieve',
                description: 'The header that you want to retrieve',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription: 'The value of the named HTTP request header.',
        syntax: 'HTTPRequestHeader(headerToRetrieve)',
        example: "%%=HTTPRequestHeader('X-Forwarded-For')=%%",
    },
];
