// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// Reassembles the full AMPscript FUNCTIONS catalog from the per-category files
// and restores the exact original source order so downstream order
// (CANONICAL_FUNCTIONS, completions) is byte-for-byte unchanged.
import { CONTENT_FUNCTIONS } from './content.js';
import { DATA_EXTENSION_FUNCTIONS } from './data-extension.js';
import { DATE_TIME_FUNCTIONS } from './date-time.js';
import { EINSTEIN_EMAIL_RECS_FUNCTIONS } from './einstein-email-recs.js';
import { ENCRYPTION_ENCODING_FUNCTIONS } from './encryption-encoding.js';
import { HTTP_FUNCTIONS } from './http.js';
import { MARKETING_CLOUD_API_FUNCTIONS } from './marketing-cloud-api.js';
import { MATH_FUNCTIONS } from './math.js';
import { MICROSOFT_DYNAMICS_FUNCTIONS } from './microsoft-dynamics.js';
import { MOBILECONNECT_FUNCTIONS } from './mobileconnect.js';
import { SALES_SERVICE_CLOUD_FUNCTIONS } from './sales-service-cloud.js';
import { SOCIAL_FUNCTIONS } from './social.js';
import { STRING_FUNCTIONS } from './string.js';
import { UTILITY_FUNCTIONS } from './utility.js';

const CATEGORY_ENTRIES = [
    ...CONTENT_FUNCTIONS,
    ...DATA_EXTENSION_FUNCTIONS,
    ...DATE_TIME_FUNCTIONS,
    ...EINSTEIN_EMAIL_RECS_FUNCTIONS,
    ...ENCRYPTION_ENCODING_FUNCTIONS,
    ...HTTP_FUNCTIONS,
    ...MARKETING_CLOUD_API_FUNCTIONS,
    ...MATH_FUNCTIONS,
    ...MICROSOFT_DYNAMICS_FUNCTIONS,
    ...MOBILECONNECT_FUNCTIONS,
    ...SALES_SERVICE_CLOUD_FUNCTIONS,
    ...SOCIAL_FUNCTIONS,
    ...STRING_FUNCTIONS,
    ...UTILITY_FUNCTIONS,
];

// Original source order of function names (preserves the curated ordering).
const ORDER = [
    'Add',
    'AddMscrmListMember',
    'AddObjectArrayItem',
    'AttachFile',
    'AttributeValue',
    'AuthenticatedEmployeeID',
    'AuthenticatedEmployeeNotificationAddress',
    'AuthenticatedEmployeeUserName',
    'AuthenticatedEnterpriseID',
    'AuthenticatedMemberID',
    'AuthenticatedMemberName',
    'BarcodeURL',
    'Base64Decode',
    'Base64Encode',
    'BeginImpressionRegion',
    'BuildOptionList',
    'BuildRowsetFromJSON',
    'BuildRowSetFromString',
    'BuildRowSetFromXML',
    'Char',
    'ClaimRow',
    'ClaimRowValue',
    'CloudPagesURL',
    'Concat',
    'ContentArea',
    'ContentAreaByName',
    'ContentBlockByID',
    'ContentBlockByKey',
    'ContentBlockByName',
    'ContentImageByID',
    'ContentImageByKey',
    'CreateMSCRMRecord',
    'CreateObject',
    'CreateSalesforceObject',
    'CreateSmsConversation',
    'DataExtensionRowCount',
    'DateAdd',
    'DateDiff',
    'DateParse',
    'DatePart',
    'DecryptSymmetric',
    'DeleteData',
    'DeleteDE',
    'DescribeMSCRMEntities',
    'DescribeMSCRMEntityAttributes',
    'Divide',
    'Domain',
    'Empty',
    'EncryptSymmetric',
    'EndImpressionRegion',
    'EndSmsConversation',
    'ExecuteFilter',
    'ExecuteFilterOrderedRows',
    'Field',
    'Format',
    'FormatCurrency',
    'FormatDate',
    'FormatNumber',
    'GetJWT',
    'GetJWTByKeyName',
    'GetPortfolioItem',
    'GetPublishedSocialContent',
    'GetSendTime',
    'GetSocialPublishURL',
    'GetSocialPublishURLByName',
    'GUID',
    'HTTPGet',
    'HTTPPost',
    'HTTPPost2',
    'HTTPPostWithRetry',
    'HTTPRequestHeader',
    'IIf',
    'Image',
    'IndexOf',
    'InsertData',
    'InsertDE',
    'InvokeCreate',
    'InvokeDelete',
    'InvokeExecute',
    'InvokePerform',
    'InvokeRetrieve',
    'InvokeUpdate',
    'IsCHTMLBrowser',
    'IsEmailAddress',
    'IsNull',
    'IsNullDefault',
    'IsPhoneNumber',
    'Length',
    'LiveContentMicrositeURL',
    'LocalDateToSystemDate',
    'LongSFID',
    'Lookup',
    'LookupOrderedRows',
    'LookupOrderedRowsCS',
    'LookupRows',
    'LookupRowsCS',
    'Lowercase',
    'MD5',
    'MMS_Content_URL',
    'MicrositeURL',
    'Mod',
    'Msg',
    'Multiply',
    'Noun',
    'Nouns',
    'Now',
    'Output',
    'OutputLine',
    'ProperCase',
    'QueryParameter',
    'RaiseError',
    'Random',
    'RatingStars',
    'Redirect',
    'RedirectTo',
    'RegExMatch',
    'Replace',
    'ReplaceList',
    'RequestParameter',
    'RetrieveMSCRMRecords',
    'RetrieveMSCRMRecordsFetchXML',
    'RetrieveSalesforceJobSources',
    'RetrieveSalesforceObjects',
    'Row',
    'RowCount',
    'SetObjectProperty',
    'SetSmsConversationNextKeyword',
    'SetStateMscrmRecord',
    'SHA1',
    'SHA256',
    'SHA512',
    'StringToDate',
    'StringToHex',
    'Substring',
    'Subtract',
    'SystemDateToLocalDate',
    'TransformXML',
    'TreatAsContent',
    'TreatAsContentArea',
    'Trim',
    'UpdateData',
    'UpdateDE',
    'UpdateMSCRMRecords',
    'UpdateSingleSalesforceObject',
    'Uppercase',
    'UpsertContact',
    'UpsertData',
    'UpsertDE',
    'UpsertMSCRMRecord',
    'URLEncode',
    'Verb',
    'v',
    'WAT',
    'WATP',
    'WrapLongURL',
];

const byName = new Map(CATEGORY_ENTRIES.map((f) => [f.name, f]));

/**
 * Canonical AMPscript function catalog, in original source order.
 *
 * @type {typeof CATEGORY_ENTRIES}
 */
export const FUNCTIONS = ORDER.map((name) => byName.get(name));
