// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// AMPscript FUNCTIONS — category: Math (6 entries).

export const MATH_FUNCTIONS = [
    {
        name: 'Add',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'add',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-math/mc-ampscript-reference-math-add.html',
        guideUrl: 'https://ampscript.guide/add/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/add/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Math',
        description: 'Computes the sum of two numeric values.',
        params: [
            { name: 'number1', description: 'First operand', type: 'string|number' },
            { name: 'number2', description: 'Second operand', type: 'string|number' },
        ],
        returnType: 'number',
        returnDescription: 'The numeric sum of the two operands.',
        syntax: 'Add(number1, number2)',
        example: '%%=Add(15, 27)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'Divide',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'divide',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-math/mc-ampscript-reference-math-divide.html',
        guideUrl: 'https://ampscript.guide/divide/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/divide/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Math',
        description: 'Divides the first number by the second.',
        params: [
            { name: 'dividend', description: 'Number to divide', type: 'string|number' },
            { name: 'divisor', description: 'Number to divide by', type: 'string|number' },
        ],
        returnType: 'number',
        returnDescription:
            'The quotient of the two operands. A zero divisor does not raise an error: a non-zero dividend yields the infinity symbol and a zero dividend yields NaN, so guard against a zero divisor before rendering the result.',
        syntax: 'Divide(dividend, divisor)',
        example: '%%=Divide(100, 4)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'Mod',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'modulo',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-math/mc-ampscript-reference-math-mod.html',
        guideUrl: 'https://ampscript.guide/mod/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/mod/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Math',
        description:
            'Returns the remainder after dividing the first number by the second (modulo).',
        params: [
            { name: 'dividend', description: 'Number to divide', type: 'string|number' },
            { name: 'divisor', description: 'Number to divide by', type: 'string|number' },
        ],
        returnType: 'number',
        returnDescription:
            'The remainder after dividing the first number by the second. The result takes the sign of the dividend, and a divisor of 0 yields NaN instead of raising an error.',
        syntax: 'Mod(dividend, divisor)',
        example: '%%=Mod(10, 3)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'Multiply',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'multiply',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-math/mc-ampscript-reference-math-multiply.html',
        guideUrl: 'https://ampscript.guide/multiply/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/multiply/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Math',
        description: 'Computes the product of two numeric values.',
        params: [
            { name: 'number1', description: 'First operand', type: 'string|number' },
            { name: 'number2', description: 'Second operand', type: 'string|number' },
        ],
        returnType: 'number',
        returnDescription: 'The product of the two operands.',
        syntax: 'Multiply(number1, number2)',
        example: '%%=Multiply(5, 3)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'Random',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'random',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-random.html',
        guideUrl: 'https://ampscript.guide/random/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/random/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Math',
        description:
            'Returns a random integer between the two specified values (inclusive). Both bounds must be whole numbers; a decimal bound aborts the page. The bounds may be supplied in either order.',
        params: [
            { name: 'min', description: 'Lower bound (inclusive)', type: 'string|number' },
            { name: 'max', description: 'Upper bound (inclusive)', type: 'string|number' },
        ],
        returnType: 'number',
        returnDescription: 'A random whole number within the supplied range.',
        syntax: 'Random(min, max)',
        example: '%%=Random(1, 100)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference states the bounds may be decimal numbers. On the child BU every decimal bound aborted the CloudPage with HTTP 422 — Random(1.2,1.8), Random(1,2.5), Random(1.0,3.0) and the quoted form Random("1.5","3.5") all failed, while the equivalent whole-number and numeric-string calls returned values normally. The same decimal calls also aborted on the parent BU, so this is not a child-BU limitation. Only whole-number bounds are usable at runtime.',
    },
    {
        name: 'Subtract',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'subtract',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-math/mc-ampscript-reference-math-subtract.html',
        guideUrl: 'https://ampscript.guide/subtract/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/subtract/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Math',
        description: 'Computes the difference between two numeric values.',
        params: [
            { name: 'minuend', description: 'Value to subtract from', type: 'string|number' },
            { name: 'subtrahend', description: 'Value to subtract', type: 'string|number' },
        ],
        returnType: 'number',
        returnDescription: 'The difference of the two operands.',
        syntax: 'Subtract(minuend, subtrahend)',
        example: '%%=Subtract(50, 15)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
];
