// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// AMPscript FUNCTIONS — category: MobileConnect (9 entries).

import { INF } from '../constants.js';

export const MOBILECONNECT_FUNCTIONS = [
    {
        name: 'CreateSmsConversation',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-create-sms-conversation.html',
        guideUrl: 'https://ampscript.guide/createsmsconversation/',
        minArgs: 4,
        maxArgs: 4,
        category: 'MobileConnect',
        description:
            'Initiates an SMS conversation with a contact from within a MobileConnect message. Returns true when a conversation is created inside a MobileConnect message context, and false in any other context (for example a CloudPage or email). The success path cannot be exercised outside a live MobileConnect send.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            "The out-of-context return is confirmed in two independent runtime contexts: a CloudPage on the child BU and an email render on the child BU. Being an ordinary function call (unlike Msg()/Noun()/Verb()), it compiles and evaluates in both: on the CloudPage, called with a real short code, an authorized destination number and app 'MOBILECONNECT', it returned the literal boolean false with the page rendering fully and no SMS sent; in an email body the same call rendered the literal False through the Email Preview API. This confirms the ampscript.guide claim that the function returns false outside a MobileConnect message context; the official Salesforce reference omits this and describes only the in-context behaviour (true on success, exception on failure). The success path (true, real conversation creation) requires a live MobileConnect message context and cannot be reproduced in a CloudPage or email; only the out-of-context false-return is exercisable, and it is proven. The catalogued signature was also corrected here: the four parameters are originationNumber, destinationNumber, nextKeyword and app, and the return is a boolean, not void.",
        params: [
            {
                name: 'originationNumber',
                description: 'The MobileConnect short code or long code used to send',
                type: 'string',
            },
            {
                name: 'destinationNumber',
                description: "The contact's phone number, including country code",
                type: 'string',
            },
            {
                name: 'nextKeyword',
                description: 'The keyword to set as the next conversation keyword',
                type: 'string',
            },
            {
                name: 'app',
                description: "The application for the conversation; must be 'MOBILECONNECT'",
                type: 'string',
            },
        ],
        returnType: 'boolean',
        returnDescription:
            'true when a conversation is created inside a MobileConnect message context; false in any other context (proven on a CloudPage). Fails with an exception in-context if unsuccessful.',
        syntax: 'CreateSmsConversation(originationNumber, destinationNumber, nextKeyword, app)',
        example: '%%=CreateSmsConversation("12345", MOBILE_NUMBER, "KEYWORD", "MOBILECONNECT")=%%',
    },
    {
        name: 'EndSmsConversation',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-end-sms-conversation.html',
        guideUrl: 'https://ampscript.guide/endsmsconversation/',
        minArgs: 2,
        maxArgs: 2,
        category: 'MobileConnect',
        description:
            'Ends an active SMS conversation with a contact from within a MobileConnect message. Returns true when the conversation is ended inside a MobileConnect message context, and false in any other context (for example a CloudPage or email). The success path cannot be exercised outside a live MobileConnect send.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The out-of-context return is confirmed in two independent runtime contexts: a CloudPage on the child BU and an email render on the child BU. Being an ordinary function call, it compiles and evaluates in both: on the CloudPage, called with a real short code and the authorized destination number, it returned the literal boolean false with the page rendering fully, no SMS sent and no conversation state changed; in an email body the same call rendered the literal False through the Email Preview API. This confirms the ampscript.guide claim that the function returns false outside a MobileConnect message context; the official Salesforce reference omits this and describes only the in-context behaviour (true on success, exception on failure). The success path (true, real conversation end) requires a live MobileConnect message context and cannot be reproduced in a CloudPage or email; only the out-of-context false-return is exercisable, and it is proven. The catalogued signature was corrected here: the two parameters are originationNumber and destinationNumber, and the return is a boolean, not void.',
        params: [
            {
                name: 'originationNumber',
                description: 'The MobileConnect short code or long code used to send',
                type: 'string',
            },
            {
                name: 'destinationNumber',
                description: "The contact's phone number, including country code",
                type: 'string',
            },
        ],
        returnType: 'boolean',
        returnDescription:
            'true when the conversation is ended inside a MobileConnect message context; false in any other context (proven on a CloudPage). Fails with an exception in-context if unsuccessful.',
        syntax: 'EndSmsConversation(originationNumber, destinationNumber)',
        example: '%%=EndSmsConversation("12345", MOBILE_NUMBER)=%%',
    },
    {
        name: 'MMS_Content_URL',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-mms-content-url.html',
        guideUrl: 'https://ampscript.guide/mobileconnect-data-strings/',
        minArgs: 1,
        maxArgs: 1,
        category: 'MobileConnect',
        description:
            'Returns the URL of MMS content from an inbound mobile-originated (MO) message. Only usable in MobileConnect.',
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
        officialDocsNote:
            'Could not runtime-verify on the only available context (a CloudPage GET on the child BU; no parent-BU escalation is configured on this tenant). Including an MMS_Content_URL(0) call in the injected content block aborted the whole page at compile time (HTTP 422) even when the call sat inside a non-matching IF branch, while an otherwise identical page with the call removed rendered HTTP 200. This matches the official reference, which states the function is usable only in MobileConnect and not in landing pages or other content types; there is no mobile-originated message context on a CloudPage to exercise it against.',
        params: [
            {
                name: 'position',
                description:
                    'Zero-based index of the MMS content to return; 0 returns the first attachment',
                type: 'number',
            },
        ],
        returnType: 'string',
        returnDescription: 'The URL of the requested MMS content from the inbound message.',
        syntax: 'MMS_Content_URL(position)',
        example: '%%=MMS_Content_URL(0)=%%',
    },
    {
        name: 'Msg',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-msg.html',
        guideUrl: 'https://ampscript.guide/mobileconnect-data-strings/',
        minArgs: 1,
        maxArgs: 1,
        category: 'MobileConnect',
        description:
            'Returns the content of an inbound mobile-originated (MO) message. Only usable in MobileConnect. The only accepted argument value is 0.',
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
        officialDocsNote:
            'Could not runtime-verify on the only available context (a CloudPage GET on the child BU; no parent-BU escalation is configured on this tenant). A page containing a Msg(0) call aborted at compile time (HTTP 422) even when the call sat inside a non-matching IF branch, whereas the same page with no Msg construct rendered HTTP 200 — so the abort happens at parse time, before any runtime gate. This matches the official reference, which states the function is usable only in MobileConnect and not in landing pages or other content types; a CloudPage supplies no mobile-originated message to read.',
        params: [
            {
                name: 'index',
                description: 'Message index; the only accepted value is 0 (the current message)',
                type: 'number',
            },
        ],
        returnType: 'string',
        returnDescription: 'The full content of the inbound mobile-originated message.',
        syntax: 'Msg(0)',
        example: '%%=Msg(0)=%%',
    },
    {
        name: 'Noun',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-noun.html',
        guideUrl: 'https://ampscript.guide/mobileconnect-data-strings/',
        minArgs: 1,
        maxArgs: 1,
        category: 'MobileConnect',
        description:
            'Returns a single word that follows the keyword in an inbound mobile-originated (MO) message, by position. Only usable in MobileConnect, chained off Msg(0).',
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
        officialDocsNote:
            'Could not runtime-verify on the only available context (a CloudPage GET on the child BU; no parent-BU escalation on this tenant). Noun is chained off Msg(0), and any page containing a Msg(0) construct aborts at compile time (HTTP 422) on a CloudPage while an otherwise identical page without it renders HTTP 200. This matches the official reference, which restricts the function to MobileConnect and forbids landing pages / other content types; a CloudPage supplies no mobile-originated message to parse.',
        params: [
            {
                name: 'position',
                description:
                    'Zero-based index of the word after the keyword to return (0 = first word after the keyword)',
                type: 'number',
            },
        ],
        returnType: 'string',
        returnDescription: 'The requested word that follows the keyword in the inbound message.',
        syntax: 'Msg(0).Noun(position)',
        example: '%%=Msg(0).Noun(1)=%%',
    },
    {
        name: 'Nouns',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-nouns.html',
        guideUrl: 'https://ampscript.guide/mobileconnect-data-strings/',
        minArgs: 0,
        maxArgs: 0,
        category: 'MobileConnect',
        description:
            'Returns all message content that follows the keyword in an inbound mobile-originated (MO) message. Only usable in MobileConnect, chained off Msg(0). Takes no arguments.',
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
        officialDocsNote:
            'Could not runtime-verify on the only available context (a CloudPage GET on the child BU; no parent-BU escalation on this tenant). Nouns is chained off Msg(0), and any page containing a Msg(0) construct aborts at compile time (HTTP 422) on a CloudPage while an otherwise identical page without it renders HTTP 200. This matches the official reference, which restricts the function to MobileConnect and forbids landing pages / other content types; a CloudPage supplies no mobile-originated message to parse.',
        params: [],
        returnType: 'string',
        returnDescription: 'All content that follows the keyword in the inbound message.',
        syntax: 'Msg(0).Nouns',
        example: '%%=Msg(0).Nouns=%%',
    },
    {
        name: 'SetSmsConversationNextKeyword',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-set-sms-conversation-next-keyword.html',
        guideUrl: 'https://ampscript.guide/setsmsconversationnextkeyword/',
        minArgs: 3,
        maxArgs: 3,
        category: 'MobileConnect',
        description:
            'Sets the keyword for the next path of an existing SMS conversation, applied when the contact next replies. Does not create a new conversation. Returns true when set inside a MobileConnect message context, and false in any other context (for example a CloudPage or email). The success path cannot be exercised outside a live MobileConnect send.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The out-of-context return is confirmed in two independent runtime contexts: a CloudPage on the child BU and an email render on the child BU. Being an ordinary function call, it compiles and evaluates in both: on the CloudPage, called with a real short code, the authorized destination number and a keyword, it returned the literal boolean false with the page rendering fully, no SMS sent and no conversation state changed; in an email body the same call rendered the literal False through the Email Preview API. This confirms the ampscript.guide claim that the function returns false outside a MobileConnect message context; the official Salesforce reference omits this and describes only the in-context behaviour. The success path (true, keyword actually set) requires a live MobileConnect message context and cannot be reproduced in a CloudPage or email; only the out-of-context false-return is exercisable, and it is proven. The catalogued signature was corrected here: the three parameters are originationNumber, destinationNumber and keyword, and the return is a boolean, not void. A docUrl to the official reference was also added.',
        params: [
            {
                name: 'originationNumber',
                description: 'The MobileConnect short code or long code used to send',
                type: 'string',
            },
            {
                name: 'destinationNumber',
                description: "The contact's phone number, including country code",
                type: 'string',
            },
            {
                name: 'keyword',
                description: 'The string to set as the next conversation keyword',
                type: 'string',
            },
        ],
        returnType: 'boolean',
        returnDescription:
            'true when the next keyword is set inside a MobileConnect message context; false in any other context (proven on a CloudPage). Fails with an exception in-context if unsuccessful.',
        syntax: 'SetSmsConversationNextKeyword(originationNumber, destinationNumber, keyword)',
        example: '%%=SetSmsConversationNextKeyword("12345", MOBILE_NUMBER, "EXAMPLE")=%%',
    },
    {
        name: 'UpsertContact',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-contacts/mc-ampscript-reference-contacts-upsert-contact.html',
        guideUrl: 'https://ampscript.guide/upsertcontact/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/upsertcontact/',
        minArgs: 5,
        maxArgs: INF,
        category: 'MobileConnect',
        description:
            "Upserts attributes onto a mobile contact matched by phone number. If the contact exists it is updated; otherwise a new contact is created. Returns a status code: 0 when the upsert succeeds and 1 when an error occurs. The only supported channel is 'mobile' and the only supported match attribute is 'phone'. An unknown attribute name returns the error status without writing anything.",
        isConfirmed: true,
        differsFromOfficialDocs: false,
        officialDocsNote:
            'Both return tokens were runtime-proven on the child BU. The success status 0 was proven by creating a brand-new mobile contact keyed on an opaque, unreachable phone number in a reserved test range with a documented system attribute (_ZipCode); calling the same key a second time with a different value updated that contact and again returned 0, so both the create and update branches of the upsert return 0. The error status 1 was proven three independent ways (unsupported channel, unsupported match attribute, non-numeric phone) and again by passing an attribute name that is not a defined MobileConnect attribute — each returned 1 with the page rendering fully and no write performed. The return is a status code (0 success / 1 error), not a count of records. The phone-number argument accepts both an integer literal and a numeric string (both returned 0 for a successful create). runtime matches the official reference, so differsFromOfficialDocs stays false.',
        params: [
            {
                name: 'channel',
                description: "The contact channel. The only supported value is 'mobile'",
                type: 'string',
            },
            {
                name: 'attribute',
                description:
                    "The attribute to use to match the contact. The only supported value is 'phone'",
                type: 'string',
            },
            {
                name: 'phoneNumber',
                description: 'The phone number of the contact, including the country code',
                type: 'string|number',
            },
            {
                name: 'keyToUpsert1',
                description: 'The name of the attribute to upsert',
                type: 'string',
            },
            {
                name: 'valueToUpsert1',
                description: 'The value of the attribute to upsert',
                type: 'string',
            },
            {
                name: 'keyToUpsertN',
                mcnSince: null,
                mcnNotes: null,
                description: 'Additional attribute name',
                type: 'string',
                optional: true,
            },
            { name: 'valueToUpsertN', description: 'Additional attribute value', optional: true },
        ],
        returnType: 'number',
        returnEnum: [0, 1],
        returnDescription:
            'A status code: 0 when the upsert succeeds (both creating a new contact and updating an existing one), 1 when an error occurs. Both tokens were proven at runtime.',
        repeat: [{ startIndex: 3, groupSize: 2, minGroups: 1 }],
        syntax: 'UpsertContact(channel, attribute, phoneNumber, keyToUpsert1, valueToUpsert1[, keyToUpsertN, valueToUpsertN, ...])',
        example: "%%=UpsertContact('mobile', 'phone', 14255550142, '_ZipCode', '98026')=%%",
    },
    {
        name: 'Verb',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sms/mc-ampscript-reference-sms-verb.html',
        guideUrl: 'https://ampscript.guide/mobileconnect-data-strings/',
        minArgs: 0,
        maxArgs: 0,
        category: 'MobileConnect',
        description:
            'Returns the keyword (verb) from an inbound mobile-originated (MO) message. Only usable in MobileConnect, chained off Msg(0). Takes no arguments.',
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
        officialDocsNote:
            'Could not runtime-verify on the only available context (a CloudPage GET on the child BU; no parent-BU escalation on this tenant). Verb is chained off Msg(0), and any page containing a Msg(0) construct aborts at compile time (HTTP 422) on a CloudPage while an otherwise identical page without it renders HTTP 200. This matches the official reference, which restricts the function to MobileConnect and forbids landing pages / other content types; a CloudPage supplies no mobile-originated message to parse.',
        params: [],
        returnType: 'string',
        returnDescription: 'The keyword (first word) of the inbound mobile-originated message.',
        syntax: 'Msg(0).Verb',
        example: '%%=Msg(0).Verb=%%',
    },
];
