// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// AMPscript FUNCTIONS — category: String (12 entries).

import { INF } from '../constants.js';

export const STRING_FUNCTIONS = [
    {
        name: 'Char',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: 'char',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-char.html',
        guideUrl: 'https://ampscript.guide/char/',
        minArgs: 1,
        maxArgs: 2,
        category: 'String',
        description:
            'Returns the character for the given numeric character code. Codes above 255 are not rejected — they resolve to the matching Unicode character.',
        params: [
            {
                name: 'characterCode',
                description: 'Character code, as a whole number',
                type: 'string|number',
            },
            {
                name: 'numRepetitions',
                mcnSince: null,
                mcnNotes: null,
                description: 'Number of times to repeat the returned character, as a whole number',
                type: 'string|number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The character for the supplied code, repeated when a repetition count is given. A count of 0 yields an empty string.',
        syntax: 'Char(characterCode[, numRepetitions])',
        example: '%%=Char(10)=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/char/',
    },
    {
        name: 'Concat',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'concat',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-concat.html',
        guideUrl: 'https://ampscript.guide/concat/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/concat/',
        minArgs: 1,
        maxArgs: INF,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'String',
        description: 'Concatenates two or more string values.',
        params: [
            { name: 'string1', description: 'First string', type: 'string|number|date' },
            {
                name: 'string2',
                description: 'Second string',
                type: 'string|number|date',
                optional: true,
            },
            {
                name: 'stringN',
                description: 'Additional string',
                type: 'string|number|date',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The concatenation of all supplied values as a single string.',
        repeat: [{ startIndex: 0, groupSize: 1, minGroups: 1 }],
        syntax: 'Concat(string1, string2[, stringN, ...])',
        example: "%%=Concat('Hello', ' ', 'World')=%%",
    },
    {
        name: 'IndexOf',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'indexOf',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-index-of.html',
        guideUrl: 'https://ampscript.guide/indexof/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/indexof/',
        minArgs: 2,
        maxArgs: 3,
        category: 'String',
        description:
            'Returns the 1-based position of a substring, matching case-insensitively. An undocumented third argument selects which occurrence to locate.',
        params: [
            {
                name: 'sourceString',
                description: 'String to search in',
                type: 'string|number',
            },
            { name: 'substring', description: 'Substring to find', type: 'string|number' },
            {
                name: 'occurrence',
                description: 'Which occurrence to locate, as a whole number; defaults to the first',
                type: 'string|number',
            },
        ],
        returnType: 'number',
        returnDescription:
            'The 1-based position of the substring, or 0 when it is not found or the requested occurrence does not exist.',
        syntax: 'IndexOf(sourceString, substring[, occurrence])',
        example: "%%=IndexOf('Hello World', 'World')=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'Length',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'length',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-length.html',
        guideUrl: 'https://ampscript.guide/length/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/length/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'String',
        description: 'Returns the number of characters in a string.',
        params: [
            {
                name: 'sourceString',
                description: 'String to measure',
                type: 'string|number|date',
            },
        ],
        returnType: 'number',
        returnDescription:
            'The number of UTF-16 code units in the string, so characters outside the Basic Multilingual Plane (such as emoji) count as 2.',
        syntax: 'Length(sourceString)',
        example: "%%=Length('Hello')=%%",
    },
    {
        name: 'Lowercase',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'lowercase',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-lowercase.html',
        guideUrl: 'https://ampscript.guide/lowercase/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/lowercase/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'String',
        description: 'Converts a string to all lowercase characters.',
        params: [
            {
                name: 'sourceString',
                description: 'String to convert',
                type: 'string|number|date',
            },
        ],
        returnType: 'string',
        returnDescription: 'The string converted to lower case.',
        syntax: 'Lowercase(sourceString)',
        example: "%%=Lowercase('HELLO')=%%",
    },
    {
        name: 'ProperCase',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'properCase',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-propercase.html',
        guideUrl: 'https://ampscript.guide/propercase/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/propercase/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'String',
        description:
            'Converts a value to proper (title) case. Every letter after the first of a word is forced to lower case, so existing internal capitals are lost.',
        params: [
            { name: 'sourceString', description: 'Value to convert', type: 'string|number|date' },
        ],
        returnType: 'string',
        returnDescription:
            'The value with the first letter of each word capitalized and the rest lower-cased.',
        syntax: 'ProperCase(sourceString)',
        example: "%%=ProperCase('hello world')=%%",
    },
    {
        name: 'RegExMatch',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-regex-match.html',
        guideUrl: 'https://ampscript.guide/regexmatch/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/regexmatch/',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        minArgs: 3,
        maxArgs: INF,
        category: 'String',
        description:
            'Returns the first occurrence of a regular expression match in a string, selected by capture group. Matching is case-sensitive unless the IgnoreCase option is passed.',
        params: [
            {
                name: 'sourceString',
                description: 'String to match against',
                type: 'string|number',
            },
            {
                name: 'regExPattern',
                description: 'The regular expression to use in the search',
                type: 'string',
            },
            {
                name: 'returnValue',
                description:
                    'Index or name of the capture group to return; 0 returns the whole match',
                type: 'string|number',
            },
            {
                name: 'regExOptions',
                description:
                    'A .NET RegexOptions member name to apply to the search, such as IgnoreCase or Multiline',
                type: 'string',
                optional: true,
            },
            {
                name: 'regExOptionsN',
                description: 'Additional RegexOptions member name',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The text of the selected capture group, or an empty string when the pattern does not match or the group does not exist.',
        repeat: [{ startIndex: 3, groupSize: 1, minGroups: 0 }],
        syntax: 'RegExMatch(sourceString, regExPattern, returnValue[, regExOptions, ...])',
        example:
            'Var @couponCode, @regEx, @regExMatch\n' +
            'Set @couponCode = "SAVE23"\n' +
            'Set @regEx = "^[A-Z0-9]{5,7}$"\n' +
            'Set @regExMatch = RegExMatch(@couponCode, @regEx, 0, "IgnoreCase")',
    },
    {
        name: 'Replace',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'replace',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-replace.html',
        guideUrl: 'https://ampscript.guide/replace/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/replace/',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        minArgs: 2,
        maxArgs: 3,
        category: 'String',
        description:
            'Replaces all occurrences of a substring with a new value, matching case-insensitively. The source is scanned once, so text formed by a replacement is not replaced again.',
        params: [
            { name: 'sourceString', description: 'Source string', type: 'string|number' },
            { name: 'searchSubstring', description: 'Substring to find', type: 'string|number' },
            {
                name: 'replacementSubstring',
                description: 'Replacement string. If omitted, the search text is removed.',
                type: 'string|number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The string with every occurrence of the search text replaced, or the source unchanged when the search text is not found.',
        syntax: 'Replace(sourceString, searchSubstring[, replacementSubstring])',
        example: "%%=Replace('Hello World', 'World', 'There')=%%",
    },
    {
        name: 'ReplaceList',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-replace-list.html',
        guideUrl: 'https://ampscript.guide/replacelist/',
        minArgs: 3,
        maxArgs: INF,
        category: 'String',
        description:
            'Replaces every occurrence of each supplied search value with one common replacement value, matching case-insensitively. The search values are applied one after another in the order given, so text produced by an earlier replacement can still be matched by a later one.',
        params: [
            { name: 'sourceString', description: 'Source string', type: 'string|number' },
            { name: 'replacementString', description: 'Replacement string', type: 'string|number' },
            { name: 'searchString1', description: 'First value to replace', type: 'string|number' },
            {
                name: 'searchStringN',
                description: 'Additional value to replace',
                type: 'string|number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The string with every supplied search value replaced by the replacement, or the source unchanged when none of them is found.',
        repeat: [{ startIndex: 2, groupSize: 1, minGroups: 1 }],
        syntax: 'ReplaceList(sourceString, replacementString, searchString1[, searchStringN, ...])',
        example: "%%=ReplaceList('a-b/c', '_', '-', '/')=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/replacelist/',
    },
    {
        name: 'Substring',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'substring',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-substring.html',
        guideUrl: 'https://ampscript.guide/substring/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/substring/',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        minArgs: 2,
        maxArgs: 3,
        category: 'String',
        description:
            'Extracts a portion of a string starting at the given index for the specified length. A start position below 1 is treated as the first character.',
        params: [
            { name: 'sourceString', description: 'Source string', type: 'string|number' },
            {
                name: 'startPosition',
                description: '1-based start position, as a whole number',
                type: 'string|number',
            },
            {
                name: 'substringLength',
                mcnSince: 67,
                mcnNotes: null,
                description:
                    'Number of characters to extract, as a whole number. If omitted, returns the remainder of the string.',
                type: 'string|number',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The requested portion of the string, or an empty string when the start position is past the end of the source.',
        syntax: 'Substring(sourceString, startPosition[, substringLength])',
        example: "%%=Substring('Hello World', 1, 5)=%%",
    },
    {
        name: 'Trim',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'trim',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-trim.html',
        guideUrl: 'https://ampscript.guide/trim/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/trim/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'String',
        description:
            'Removes leading and trailing whitespace from a value. Tabs, line breaks and the non-breaking space count as whitespace.',
        params: [
            { name: 'sourceString', description: 'Value to trim', type: 'string|number|date' },
        ],
        returnType: 'string',
        returnDescription: 'The string with leading and trailing whitespace removed.',
        syntax: 'Trim(sourceString)',
        example: "%%=Trim('  hello  ')=%%",
    },
    {
        name: 'Uppercase',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'uppercase',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-uppercase.html',
        guideUrl: 'https://ampscript.guide/uppercase/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/uppercase/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'String',
        description:
            'Converts a string to all uppercase characters. The German sharp s remains unchanged rather than expanding to SS.',
        params: [
            {
                name: 'sourceString',
                description: 'String to convert',
                type: 'string|number|date',
            },
        ],
        returnType: 'string',
        returnDescription: 'The string converted to upper case.',
        syntax: 'Uppercase(sourceString)',
        example: "%%=Uppercase('hello')=%%",
    },
];
