// AUTO-SPLIT from the original single-file src/index.js. Data moved verbatim.
// AMPscript FUNCTIONS — category: Utility (32 entries).

import { INF } from '../constants.js';

export const UTILITY_FUNCTIONS = [
    {
        name: 'AttributeValue',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: 'personalizationResult',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-attribute-value.html',
        guideUrl: 'https://ampscript.guide/attributevalue/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/attributevalue/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Reads an attribute of the current message or page context by name, giving an empty value instead of failing when the name is unknown. The name is matched without regard to case, and system attributes such as the message context resolve on a CloudPage even though no subscriber is involved.',
        params: [
            {
                name: 'attributeName',
                description:
                    'Attribute name, matched without regard to case; an empty name aborts the page',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The attribute value as a string, or an empty value when the name resolves to nothing.',
        syntax: 'AttributeValue(attributeName)',
        example: "%%=AttributeValue('firstname')=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'AuthenticatedEmployeeID',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-authenticated-employee-id.html',
        guideUrl: 'https://ampscript.guide/authenticatedemployeeid/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Returns the numeric employee ID of the Marketing Cloud user tied to the current context. On a public CloudPage, where nobody is signed in, it still returns a non-empty ID rather than an empty value, so it cannot be used to tell an authenticated visitor apart from an anonymous one.',
        params: [],
        returnType: 'string',
        returnDescription:
            'The employee ID as a numeric string, usable directly in Concat and in comparisons. It was non-empty even without a signed-in visitor.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/authenticatedemployeeid/',
        syntax: 'AuthenticatedEmployeeID()',
        example: '%%=AuthenticatedEmployeeID()=%%',
    },
    {
        name: 'AuthenticatedEmployeeNotificationAddress',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-authenticated-employee-notification-address.html',
        guideUrl: 'https://ampscript.guide/authenticatedemployeenotificationaddress/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Returns the notification email address of the Marketing Cloud user tied to the current context. On a public CloudPage, where nobody is signed in, it still returns a non-empty address rather than an empty value, so it cannot be used to tell an authenticated visitor apart from an anonymous one. It is a separate value from AuthenticatedEmployeeUserName() — neither can be derived from the other.',
        params: [],
        returnType: 'string',
        returnDescription:
            'The notification address as a string, usable directly in Concat and in comparisons. On the business unit tested it was a real email address on a registered domain, and it was non-empty even without a signed-in visitor.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Proven on the child BU; the parent BU was not needed. The official reference scopes the function to microsites that use sender authenticated redirection and explicitly says it is not for use with CloudPages. At runtime the opposite happened: an anonymous GET of a public CloudPage rendered at HTTP 200 and the call returned a well-formed, non-empty notification email address — Empty() answered false, Length() reported 29 characters and IsEmailAddress() accepted it. The value behaved as an ordinary string when used inline, nested inside Concat and compared against the empty string. The literal address is redacted here because it identifies an account user; only its shape is described.',
        sfmcGuideUrl:
            'https://sfmc.guide/engagement/ampscript/functions/authenticatedemployeenotificationaddress/',
        syntax: 'AuthenticatedEmployeeNotificationAddress()',
        example: '%%=AuthenticatedEmployeeNotificationAddress()=%%',
    },
    {
        name: 'AuthenticatedEmployeeUserName',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-authenticated-employee-username.html',
        guideUrl: 'https://ampscript.guide/authenticatedemployeeusername/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Returns the login username of the Marketing Cloud user tied to the current context. On a public CloudPage, where nobody is signed in, it still returns a non-empty username rather than an empty value, so it cannot be used to tell an authenticated visitor apart from an anonymous one.',
        params: [],
        returnType: 'string',
        returnDescription:
            'The username as a string, usable directly in Concat and in comparisons. On the business unit tested it was shaped like an email address and was non-empty even without a signed-in visitor.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl:
            'https://sfmc.guide/engagement/ampscript/functions/authenticatedemployeeusername/',
        syntax: 'AuthenticatedEmployeeUserName()',
        example: '%%=AuthenticatedEmployeeUserName()=%%',
    },
    {
        name: 'AuthenticatedEnterpriseID',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-authenticated-enterprise-id.html',
        guideUrl: 'https://ampscript.guide/authenticatedenterpriseid/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Returns the enterprise ID (EID) of the Marketing Cloud account tied to the current context. On a public CloudPage, where nobody is signed in, it still returns a non-empty ID rather than an empty value, so it cannot be used to tell an authenticated visitor apart from an anonymous one. Called from a child business unit it reports the parent (enterprise) MID, not the child MID, and it is a different value from AuthenticatedEmployeeID().',
        params: [],
        returnType: 'string',
        returnDescription:
            'The enterprise ID as a digits-only numeric string, usable directly in Concat, in comparisons and in arithmetic. It was non-empty even without a signed-in visitor.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl:
            'https://sfmc.guide/engagement/ampscript/functions/authenticatedenterpriseid/',
        syntax: 'AuthenticatedEnterpriseID()',
        example: '%%=AuthenticatedEnterpriseID()=%%',
    },
    {
        name: 'AuthenticatedMemberID',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-authenticated-member-id.html',
        guideUrl: 'https://ampscript.guide/authenticatedmemberid/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/authenticatedmemberid/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Returns the member ID (MID) of the business unit the code runs on. On a public CloudPage, where nobody is signed in, it still returns a non-empty MID rather than an empty value, so it cannot be used to tell an authenticated visitor apart from an anonymous one. Called from a child business unit it reports that CHILD MID, unlike AuthenticatedEnterpriseID(), which reports the parent (enterprise) MID in the same render.',
        params: [],
        returnType: 'string',
        returnDescription:
            'The member ID as a digits-only numeric string, usable directly in Concat, in comparisons and in arithmetic. It was non-empty even without a signed-in visitor.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        syntax: 'AuthenticatedMemberID()',
        example: '%%=AuthenticatedMemberID()=%%',
    },
    {
        name: 'AuthenticatedMemberName',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-authenticated-member-name.html',
        guideUrl: 'https://ampscript.guide/authenticatedmembername/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/authenticatedmembername/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Returns the display name of the business unit the code runs on. On a public CloudPage, where nobody is signed in, it still returns a non-empty name rather than an empty value, so it cannot be used to tell an authenticated visitor apart from an anonymous one. It is the business unit name as shown in the Marketing Cloud UI — spaces and punctuation included — not a person and not the login username returned by AuthenticatedEmployeeUserName() in the same render.',
        params: [],
        returnType: 'string',
        returnDescription:
            'The business unit display name as a free-text string that can contain spaces and punctuation, usable directly in Concat and in comparisons. It was non-empty even without a signed-in visitor.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        syntax: 'AuthenticatedMemberName()',
        example: '%%=AuthenticatedMemberName()=%%',
    },
    {
        name: 'CloudPagesURL',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-cloud-pages-url.html',
        guideUrl: 'https://ampscript.guide/cloudpagesurl/',
        minArgs: 1,
        maxArgs: INF,
        category: 'Utility',
        description:
            'Builds the published URL of a CloudPages landing page. Name-value pairs are appended in PAIRS and are folded into a single encrypted query token rather than readable parameters; an odd trailing argument or a page ID that matches no page aborts the page.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/cloudpagesurl/',
        params: [
            {
                name: 'pageId',
                description: 'CloudPages page ID (number or string)',
                type: 'string|number',
            },
            {
                name: 'paramName1',
                description: 'Query parameter name',
                type: 'string',
                optional: true,
            },
            {
                name: 'paramValue1',
                description: 'Query parameter value',
                type: 'string',
                optional: true,
            },
            {
                name: 'paramNameN',
                description: 'Additional query parameter name',
                type: 'string',
                optional: true,
            },
            {
                name: 'paramValueN',
                description: 'Additional query parameter value',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The page URL. With no extra pairs it is the bare published URL; with pairs it carries one encrypted query token that changes on every call, so the result must never be compared or cached.',
        repeat: [{ startIndex: 1, groupSize: 2, minGroups: 0 }],
        syntax: 'CloudPagesURL(pageId[, paramName1, paramValue1, paramNameN, paramValueN, ...])',
        example: "%%=CloudPagesURL(123, 'key', 'value')=%%",
    },
    {
        name: 'Domain',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-domain.html',
        guideUrl: 'https://ampscript.guide/domain/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/domain/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'Utility',
        description:
            'Returns everything after the first at sign, without validating the address or the domain. A value with no at sign, an empty string and a number all return an empty string.',
        params: [
            {
                name: 'emailAddress',
                description: 'Email address; the text after the first at sign is returned verbatim',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The text following the first at sign, preserving the original case and any further at signs. Empty when the value contains no at sign or nothing follows it.',
        syntax: 'Domain(emailAddress)',
        example: "%%=Domain('user@example.com')=%%",
    },
    {
        name: 'Empty',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'isEmpty',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-empty.html',
        guideUrl: 'https://ampscript.guide/empty/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/empty/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Returns true when the value is an empty string, an unset variable, or an undeclared variable. Whitespace, the number 0, the string "0" and the string "false" are all treated as present.',
        params: [
            {
                name: 'value',
                description:
                    'Value to test; a variable, literal, attribute or nested function call is accepted',
                type: 'string|number|boolean|date',
            },
        ],
        returnType: 'boolean',
        returnDescription: 'True when the value is empty or missing, otherwise false.',
        returnEnum: [true, false],
        isConfirmed: true,
        syntax: 'Empty(value)',
        example: '%%=Empty(@myVar)=%%',
    },
    {
        name: 'Format',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'format',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-string/mc-ampscript-reference-string-format.html',
        guideUrl: 'https://ampscript.guide/format/',
        minArgs: 2,
        maxArgs: 4,
        category: 'Utility',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Proven on the child BU. The official reference names two possible values for the third parameter, Date and Number, but at runtime only Date is usable. Passing the literal Number aborts the page with HTTP 422 and discards all output, whether or not a locale follows it — Format(1234.555, "C2", "Number") and Format(1234.555, "C2", "Number", "de-DE") both aborted, exactly like the invented value Banana. Date works in any capitalisation, and the empty string works and still allows a locale in the fourth parameter, so Format(1234.555, "C2", "", "de-DE") is the way to format a localised number. Number formatting also happens correctly with the third parameter omitted entirely, so the documented value is not merely optional, it is unusable.',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/format/',
        description:
            'Formats a number, a date or a string with a .NET format pattern. The third parameter only accepts Date or the empty string; the documented value Number aborts the page.',
        params: [
            {
                name: 'value',
                description:
                    'The value to format; a number, a numeric string, a date value or a parseable date string',
                type: 'string|number|date',
            },
            {
                name: 'formatString',
                description:
                    'Standard or custom .NET format pattern; an unusable pattern is echoed back instead of failing',
                type: 'string',
            },
            {
                name: 'dataFormat',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Only Date, in any capitalisation, or the empty string; any other value including the documented Number aborts the page',
                type: 'string',
                optional: true,
            },
            {
                name: 'cultureCode',
                description:
                    'The locale for separators, symbols and month and day names, written with either a hyphen or an underscore',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The formatted value, or an unformatted echo of the input or of the pattern when the pattern does not suit the input.',
        syntax: 'Format(value, formatString[, dataFormat, cultureCode])',
        example: '%%=Format("2026-03-04 13:52:07", "yyyy-MM-dd HH:mm:ss", "Date")=%%',
    },
    {
        name: 'FormatCurrency',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'formatCurrency',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-formatCurrency.html',
        guideUrl: 'https://ampscript.guide/formatcurrency/',
        minArgs: 2,
        maxArgs: 4,
        category: 'Utility',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/formatcurrency/',
        description:
            'Formats a number as a currency amount for a locale, choosing the symbol, the separators and the symbol position from that locale. Rounding is half-up.',
        params: [
            {
                name: 'value',
                description:
                    'The amount to format, as a number or as a numeric string; a string may carry thousands separators',
                type: 'string|number',
            },
            {
                name: 'locale',
                description:
                    'The locale that supplies the symbol, the separators and the symbol position, written with either a hyphen or an underscore; a language-only code works and an unknown code falls back to a generic currency sign',
                type: 'string',
            },
            {
                name: 'decimalPlaces',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'Number of decimal places; without it the locale decides, which is zero places for currencies that have no minor unit',
                type: 'string|number',
                optional: true,
                default: 2,
            },
            {
                name: 'symbol',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "Replaces the locale's currency symbol while keeping the locale's separators and symbol position; requires decimalPlaces to be supplied as well",
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The amount formatted as a currency string for the requested locale.',
        syntax: 'FormatCurrency(value, locale[, decimalPlaces, symbol])',
        example: "%%=FormatCurrency(1234.555, 'en-US')=%%",
    },
    {
        name: 'FormatNumber',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'formatNumber',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-formatNumber.html',
        guideUrl: 'https://ampscript.guide/formatnumber/',
        minArgs: 2,
        maxArgs: 3,
        category: 'Utility',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/formatnumber/',
        description:
            'Formats a number with a standard or custom .NET numeric pattern, optionally for a locale. Rounding is half-up.',
        params: [
            {
                name: 'number',
                description:
                    'The value to format, as a number or as a numeric string; a string may carry thousands separators',
                type: 'string|number',
            },
            {
                name: 'format',
                description:
                    'Standard pattern letter with an optional precision digit, such as N2 or C0, or a custom pattern; an unrecognised pattern is echoed back',
                type: 'string',
            },
            {
                name: 'locale',
                description:
                    'The locale that supplies separators and the currency symbol, written with either a hyphen or an underscore; an unknown code falls back rather than failing',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription: 'The number formatted according to the supplied pattern.',
        syntax: 'FormatNumber(number, format[, locale])',
        example: "%%=FormatNumber(1234.555, 'N2', 'de-DE')=%%",
    },
    {
        name: 'GUID',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-guid.html',
        guideUrl: 'https://ampscript.guide/guid/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/guid/',
        minArgs: 0,
        maxArgs: 0,
        category: 'Utility',
        description:
            'Generates a new globally unique identifier. Every call returns a different value, so store the result in a variable when the same identifier is needed twice.',
        params: [],
        returnType: 'string',
        returnDescription:
            'A 36-character lowercase identifier in the eight-four-four-four-twelve hyphenated form, without surrounding braces.',
        syntax: 'GUID()',
        example: '%%=GUID()=%%',
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'IIf',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'iif',
        handlebarsExact: true,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-iif.html',
        guideUrl: 'https://ampscript.guide/iif/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/iif/',
        minArgs: 3,
        maxArgs: 3,
        category: 'Utility',
        description:
            'Returns one of two values based on a boolean expression (inline if). Only a real comparison or a boolean-returning function selects the true branch; a plain string or number always selects the false branch. Only the selected branch is evaluated, so a call that would abort the page is safe in the branch that is not taken.',
        params: [
            {
                name: 'expression',
                description:
                    'Boolean expression to evaluate; a non-boolean value always selects the false branch',
                type: 'boolean',
            },
            {
                name: 'trueValue',
                description: 'Value returned when true; evaluated only when true is selected',
                type: 'string|number|boolean|date',
            },
            {
                name: 'falseValue',
                description: 'Value returned when false; evaluated only when false is selected',
                type: 'string|number|boolean|date',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The second argument when the condition is true, otherwise the third argument.',
        isConfirmed: true,
        syntax: 'IIf(expression, trueValue, falseValue)',
        example: "%%=IIf(Empty(@name), 'Friend', @name)=%%",
    },
    {
        name: 'IsCHTMLBrowser',
        supportedInCloudPage: true,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-is-chtml-browser.html',
        guideUrl: 'https://ampscript.guide/ischtmlbrowser/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/ischtmlbrowser/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference documents this as an AMPscript function without noting that it is restricted to non-sendable content. Email/send-context finding: rendered through the Email Preview API against a seeded sendable row, an isolated IsCHTMLBrowser("DoCoMo/2.0 N905i") was rejected with HTTP 400 errorcode 10004 ("IsCHTMLBrowser Function is not valid in content. This function is only allowed in non sendable content."). So it works only in non-sendable content (CloudPages / landing pages) and cannot be used inside a sendable email, which fits its purpose since a user-agent is a request-time value absent at send time.',
        category: 'Utility',
        description:
            'Tests a user agent string for a compact HTML (cHTML) feature-phone browser. Feature-phone agents such as i-mode and KDDI handsets are recognised; modern desktop and mobile agents are not. Only valid in non-sendable content (CloudPages / landing pages), not in sendable email.',
        params: [
            {
                name: 'userAgent',
                description:
                    'User agent string to test, typically HTTPRequestHeader("user-agent") on a CloudPage',
                type: 'string',
            },
        ],
        returnType: 'boolean',
        returnDescription: 'True when the user agent indicates a cHTML browser, otherwise false.',
        returnEnum: [true, false],
        syntax: 'IsCHTMLBrowser(userAgent)',
        example: '%%=IsCHTMLBrowser(@userAgent)=%%',
    },
    {
        name: 'IsEmailAddress',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-is-email-address.html',
        guideUrl: 'https://ampscript.guide/isemailaddress/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/isemailaddress/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference states that an address whose domain has no top-level domain is accepted, giving a call on a bare single-label domain as an example of a true result. On a live Engagement CloudPage on the child business unit that shape returned False, in a gate that printed its own start and done markers at HTTP 200 alongside a known-good control block. Every other example in the same table matched: the missing at sign, the double at sign, the missing local part and the missing second-level domain all returned False, and a well-formed address returned True. Surrounding whitespace is also rejected, which no source mentions.',
        category: 'Utility',
        description:
            'Checks a value against email address syntax only; it never tests whether the mailbox or domain exists. Surrounding whitespace and a domain without a top-level domain are both rejected.',
        params: [
            {
                name: 'value',
                description:
                    'Value to validate; trim it first, as a leading or trailing space fails',
                type: 'string',
            },
        ],
        returnType: 'boolean',
        returnDescription:
            'True when the value is a syntactically valid email address, otherwise false.',
        returnEnum: [true, false],
        syntax: 'IsEmailAddress(value)',
        example: "%%=IsEmailAddress('test@example.com')=%%",
    },
    {
        name: 'IsNull',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'isEmpty',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-is-null.html',
        guideUrl: 'https://ampscript.guide/isnull/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/isnull/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Returns true only for a genuine null, which in practice means a data extension field with no value. An unset or undeclared variable, an empty string, whitespace and every ordinary value all return false, so this is not a general emptiness test.',
        params: [
            {
                name: 'value',
                description:
                    'Value to test; typically a data extension field value retrieved with Lookup',
                type: 'string|number|boolean|date',
            },
        ],
        returnType: 'boolean',
        returnDescription:
            'True when the value is null, otherwise false. Prefer Empty when the intent is to detect a missing or blank value.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference shows a variable declared with VAR and never assigned, and states IsNull returns true for it. On a live Engagement CloudPage on the child business unit that exact shape returned False, in a gate that printed its own start and done markers at HTTP 200 alongside a known-good control block. The same False came back for an undeclared variable, an empty string, whitespace, 0, "0", "false", a real value, a date, an absent attribute, an absent request parameter and the subscriber-context tokens. Use Empty for a missing-value test.',
        syntax: 'IsNull(value)',
        example: '%%=IsNull(@value)=%%',
    },
    {
        name: 'IsNullDefault',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: 'fallback',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-is-null-default.html',
        guideUrl: 'https://ampscript.guide/isnulldefault/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/isnulldefault/',
        minArgs: 2,
        maxArgs: 2,
        category: 'Utility',
        description:
            'Returns the value if not null, otherwise returns the default. Outside a Smart Capture form the default is never reached: on a CloudPage every empty-ish input returns the empty string instead, so it cannot be used as a general fallback.',
        params: [
            {
                name: 'value',
                description: 'Value to test; returned unchanged whenever it is present',
                type: 'string|number|boolean|date',
            },
            {
                name: 'defaultValue',
                description:
                    'Default to return when the value is null; only reached in a Smart Capture form context',
                type: 'string|number|boolean|date',
            },
        ],
        returnType: 'string',
        returnDescription: 'The original value, or the default value when the original is null.',
        isConfirmed: true,
        syntax: 'IsNullDefault(value, defaultValue)',
        example: "%%=IsNullDefault(@name, 'Friend')=%%",
    },
    {
        name: 'IsPhoneNumber',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-is-phone-number.html',
        guideUrl: 'https://ampscript.guide/isphonenumber/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/isphonenumber/',
        minArgs: 1,
        maxArgs: 1,
        isConfirmed: true,
        differsFromOfficialDocs: false,
        category: 'Utility',
        description:
            'Checks a value against the North American Numbering Plan. Dashes, dots, spaces and parentheses are tolerated, but a leading plus sign, any letter, a number outside the plan and a leading country-code digit all fail.',
        params: [
            {
                name: 'value',
                description:
                    'Phone number to validate; strip any leading plus sign or country code first',
                type: 'string|number',
            },
        ],
        returnType: 'boolean',
        returnDescription: 'True when the value is a valid phone number, otherwise false.',
        returnEnum: [true, false],
        syntax: 'IsPhoneNumber(value)',
        example: "%%=IsPhoneNumber('425-555-0142')=%%",
    },
    {
        name: 'MicrositeURL',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-microsite-url.html',
        guideUrl: 'https://ampscript.guide/micrositeurl/',
        minArgs: 1,
        maxArgs: INF,
        category: 'Utility',
        description:
            'Builds a Classic Content microsite URL whose single encrypted query string carries the page reference and any extra name-value pairs. Every call produces a fresh token, so two calls with identical arguments never match.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/micrositeurl/',
        params: [
            { name: 'pageId', description: 'Microsite page ID', type: 'string|number' },
            {
                name: 'paramName1',
                description: 'Query parameter name',
                type: 'string',
                optional: true,
            },
            {
                name: 'paramValue1',
                description: 'Query parameter value',
                type: 'string',
                optional: true,
            },
            {
                name: 'paramNameN',
                description: 'Additional query parameter name',
                type: 'string',
                optional: true,
            },
            {
                name: 'paramValueN',
                description: 'Additional query parameter value',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'A microsite page URL carrying one encrypted token; extra name-value pairs are folded into that token rather than appended as readable query parameters.',
        repeat: [{ startIndex: 1, groupSize: 2, minGroups: 0 }],
        syntax: 'MicrositeURL(pageId[, paramName1, paramValue1, paramNameN, paramValueN, ...])',
        example: '%%=MicrositeURL(12345)=%%',
    },
    {
        name: 'Output',
        supportedInCloudPage: true,
        supportedInEmail: false,
        mcnSince: 67,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-output.html',
        guideUrl: 'https://ampscript.guide/output/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/output/',
        minArgs: 0,
        maxArgs: INF,
        category: 'Utility',
        description:
            'Writes the result of a nested function call into the rendered content. A string literal, a bare variable or a number renders nothing at all, without raising an error.',
        params: [
            {
                name: 'content',
                description:
                    'Function call whose result is written; a literal or bare variable renders nothing',
                optional: true,
            },
            {
                name: 'contentN',
                description:
                    'Additional function call whose result is written in turn; a literal or bare variable renders nothing',
                optional: true,
            },
        ],
        returnType: 'void',
        returnDescription:
            'No value is returned, so the call cannot be nested inside another function; the result is written straight into the rendered content.',
        repeat: [{ startIndex: 0, groupSize: 1, minGroups: 0 }],
        syntax: 'Output([content, ...])',
        example: "%%=Output(Concat('Hello ', @firstName))=%%",
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference states that a value which is not a function call, such as a string literal, makes the function return an error. On a live Engagement CloudPage on the child business unit a literal argument, a bare variable and a bare number each rendered nothing at all while the page still returned HTTP 200 and every surrounding marker printed, so no error surfaced anywhere. The same page also accepted zero arguments and up to three arguments, writing each one in turn.',
    },
    {
        name: 'OutputLine',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-output-line.html',
        guideUrl: 'https://ampscript.guide/outputline/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/outputline/',
        minArgs: 0,
        maxArgs: INF,
        category: 'Utility',
        description:
            'Writes the result of a nested function call into the rendered content, followed by a carriage return and line feed. A string literal, a bare variable or a number renders only the line break. The break is not an HTML line break, so an HTML view keeps everything on one line unless the content sits inside a preformatted element.',
        params: [
            {
                name: 'content',
                description:
                    'Function call whose result is written; a literal or bare variable renders only the line break',
                optional: true,
            },
            {
                name: 'contentN',
                description:
                    'Additional function call whose result is written in turn before the single trailing line break; a literal or bare variable renders only the line break',
                optional: true,
            },
        ],
        returnType: 'void',
        returnDescription:
            'No value is returned, so the call cannot be nested inside another function; the result and a carriage return plus line feed are written straight into the rendered content.',
        repeat: [{ startIndex: 0, groupSize: 1, minGroups: 0 }],
        syntax: 'OutputLine([content, ...])',
        example: "%%=OutputLine(Concat('Hello ', @firstName))=%%",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'QueryParameter',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-query-parameter.html',
        guideUrl: 'https://ampscript.guide/queryparameter/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/queryparameter/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Returns the value of a URL query string parameter from the current page request. The name is matched without regard to case, percent-encoded characters arrive decoded, and a name supplied more than once yields the values joined by a comma.',
        params: [
            {
                name: 'parameterName',
                description: 'Query parameter name, matched without regard to case',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The decoded value of the named query-string parameter, or an empty string when the request carries no such parameter. The value is returned exactly as supplied, so escape it before rendering it into markup.',
        syntax: 'QueryParameter(parameterName)',
        example: "%%=QueryParameter('utm_source')=%%",
        isConfirmed: true,
    },
    {
        name: 'RaiseError',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: 'raiseError',
        handlebarsExact: false,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-raise-error.html',
        guideUrl: 'https://ampscript.guide/raiseerror/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/raiseerror/',
        minArgs: 1,
        maxArgs: 5,
        category: 'Utility',
        description:
            'Raises a runtime error, optionally skipping the current subscriber or returning an API error. Outside a send it is not a graceful abort: on a landing page it discards everything already written and answers the same generic failure any other aborting call gives, with the message nowhere in the response.',
        params: [
            { name: 'message', description: 'Error message', type: 'string' },
            {
                name: 'skipSubscriber',
                mcnSince: null,
                mcnNotes: null,
                description:
                    'If true, the function skips only the subscriber for which the error was raised, and proceeds with the rest of the email job. If false, the function stops the entire email job when an error is raised. The default value is false.',
                type: 'string|boolean|number',
                optional: true,
            },
            {
                name: 'apiErrorCode',
                mcnSince: null,
                mcnNotes: null,
                description: 'Custom API error code',
                type: 'string',
                optional: true,
            },
            {
                name: 'apiErrorNumber',
                mcnSince: null,
                mcnNotes: null,
                description: 'Custom API error message',
                type: 'number',
                optional: true,
            },
            {
                name: 'preserveDataExt',
                mcnSince: null,
                mcnNotes: null,
                description:
                    "If true, the function retains information written to data extensions before the error occurs, even if the subscriber is skipped. If false, the function doesn't retain data extension information recorded before the error. This parameter applies to information that is inserted, updated, upserted, or deleted using AMPscript functions",
                type: 'boolean',
                optional: true,
            },
        ],
        returnType: 'void',
        returnDescription:
            'No value is returned; processing is halted. On a landing page the whole request is abandoned and the response body is a fixed failure notice rather than the supplied message.',
        syntax: 'RaiseError(message[, skipSubscriber, apiErrorCode, apiErrorNumber, preserveDataExt])',
        example: "RaiseError('Missing required field', 0)",
        isConfirmed: true,
        differsFromOfficialDocs: false,
    },
    {
        name: 'Redirect',
        supportedInCloudPage: true,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-redirect.html',
        guideUrl: 'https://ampscript.guide/redirect/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/redirect/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Performs an HTTP redirect to the specified URL. Landing pages only. The response is a 302 whose Location is the supplied value verbatim, and everything written before the call is discarded along with the page body. Not to be confused with RedirectTo, which emits no redirect at all.',
        params: [{ name: 'url', description: 'Target URL', type: 'string|number' }],
        returnType: 'void',
        returnDescription:
            'No value is returned; the request answers 302 and the supplied value becomes the Location header unchanged, even when it is not an absolute URL.',
        syntax: 'Redirect(url)',
        example: "Redirect('https://example.com')",
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'Email/send-context finding: Redirect is not valid in sendable email content. Rendered through the Email Preview API against a seeded sendable row, an isolated Redirect("https://sfmc.guide/robots.txt") was rejected with HTTP 400 errorcode 10005 ("Redirect Function is not valid in content. This function is only allowed in in content with an HTTP context."). It is a CloudPage / landing-page (non-sendable, HTTP-context) feature that emits a 302, and cannot be used inside a sendable email, where there is no HTTP response to redirect.',
    },
    {
        name: 'RedirectTo',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-redirect-to.html',
        guideUrl: 'https://ampscript.guide/redirectto/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Marks a URL held in a variable or field as a tracked email link. It never redirects the current request and never halts the script; outside a tracked send it hands the value straight back.',
        isConfirmed: true,
        differsFromOfficialDocs: false,
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/redirectto/',
        params: [{ name: 'url', description: 'Target URL', type: 'string|number' }],
        returnType: 'string',
        returnDescription:
            'The link-tracking target for the supplied address during a tracked send; on a CloudPage the supplied value unchanged.',
        syntax: 'RedirectTo(url)',
        example: '%%=RedirectTo(@targetUrl)=%%',
    },
    {
        name: 'RequestParameter',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-sites/mc-ampscript-reference-sites-request-parameter.html',
        guideUrl: 'https://ampscript.guide/requestparameter/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/requestparameter/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Returns the value of a form post or query string parameter from the current request. The name is matched without regard to case, percent-encoded characters arrive decoded, and a name supplied more than once yields the values joined by a comma.',
        params: [
            {
                name: 'parameterName',
                description: 'Parameter name, matched without regard to case',
                type: 'string',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The decoded value of the named request parameter, or an empty string when the request carries no such parameter. The value is returned exactly as supplied, so escape it before rendering it into markup.',
        syntax: 'RequestParameter(parameterName)',
        example: "%%=RequestParameter('id')=%%",
        isConfirmed: true,
    },
    {
        name: 'v',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: 67,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-utilities/mc-ampscript-reference-utilities-v.html',
        guideUrl: 'https://ampscript.guide/v/',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/v/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Outputs a value inline, normally a variable reference. A string or number literal and a nested function call are accepted as well, each rendering its own value.',
        params: [
            {
                name: 'variableName',
                description: 'Variable reference, literal or nested function call to output',
                type: 'string|number',
            },
        ],
        returnType: 'string',
        returnDescription: 'The referenced value rendered as a string.',
        syntax: 'v(variableName)',
        example: '%%=v(@myVar)=%%',
        isConfirmed: true,
    },
    {
        name: 'WAT',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-wat.html',
        guideUrl: 'https://ampscript.guide/wat/',
        minArgs: 2,
        maxArgs: INF,
        category: 'Utility',
        description:
            'Returns the values of the Web Analytics Tracking (WAT) parameter set with the specified external key, substituting the supplied values for the matching WATP references in the Sender Profile tracking parameter.',
        params: [
            {
                name: 'parameterSetKey',
                description: 'The external key of the WAT parameter set',
                type: 'string',
            },
            {
                name: 'parameterValue1',
                description: 'Value used to replace the WATP(1) tracking parameter reference',
                type: 'string',
            },
            {
                name: 'parameterValueN',
                description: 'Additional value used to replace the WATP(N) reference',
                type: 'string',
                optional: true,
            },
        ],
        returnType: 'string',
        returnDescription:
            'The resolved Web Analytics tracking parameter value with the supplied substitutions applied.',
        repeat: [{ startIndex: 1, groupSize: 1, minGroups: 1 }],
        syntax: 'WAT(parameterSetKey, parameterValue1[, parameterValueN, ...])',
        example: "%%=WAT('Omniture', '1234', '5678')=%%",
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-test-data',
        officialDocsNote:
            'On a CloudPage every invocation aborted at HTTP 422 on both the child BU and the parent BU. An email-context render on the parent BU changed the picture: the Email Preview API RECOGNISES and evaluates the function and fails with a precise message that the named tracking parameter set does not exist (Tracking Parameter Name: Omniture). So WAT is not a broken function — it resolves a Web Analytics Tracking parameter set that must first be configured on the account (a Salesforce-support / Sender Profile setup), and none exists on these BUs to resolve. The block is a missing-test-data gate, not a broken invocation.',
    },
    {
        name: 'WATP',
        supportedInCloudPage: false,
        supportedInEmail: false,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-content/mc-ampscript-reference-content-wat.html',
        guideUrl: 'https://ampscript.guide/watp/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Ordinal placeholder for a parameter value configured in a WAT parameter set. The ordinal maps to the position of the value passed to the WAT function. Configured by Marketing Cloud Support as part of the WAT string.',
        params: [
            {
                name: 'ordinal',
                description: 'The position of the parameter value within the WAT string (1-based)',
                type: 'number',
            },
        ],
        returnType: 'string',
        returnDescription:
            'The parameter value supplied to the WAT function at the given ordinal position.',
        syntax: 'WATP(ordinal)',
        example: '%%=urlencode(WATP(1))=%%',
        isConfirmed: false,
        verificationBlocked: true,
        verificationBlockedReason: 'no-working-invocation',
    },
    {
        name: 'WrapLongURL',
        supportedInCloudPage: true,
        supportedInEmail: true,
        mcnSince: null,
        handlebarsEquivalent: null,
        mcnNotes: null,
        docUrl: 'https://developer.salesforce.com/docs/marketing/marketing-cloud-ampscript/references/mc-ampscript-http/mc-ampscript-reference-http-wrap-long-url.html',
        guideUrl: 'https://ampscript.guide/wraplongurl/',
        minArgs: 1,
        maxArgs: 1,
        category: 'Utility',
        description:
            'Shortens a long URL for email clients that truncate long hyperlinks. Outside an email send the argument comes back unchanged, so a CloudPage never sees a shortened link.',
        isConfirmed: true,
        differsFromOfficialDocs: true,
        officialDocsNote:
            'The official reference states that a URL longer than 975 characters comes back as a shortened link that redirects through the platform. On a live Engagement CloudPage on the child business unit a 1048-character URL was returned byte for byte unchanged at the same length, twice in one render, and the same held for a 27-character URL, an empty string and a string that is not a URL at all. The community guide notes that shortening only happens on a send, which the official page does not mention.',
        sfmcGuideUrl: 'https://sfmc.guide/engagement/ampscript/functions/wraplongurl/',
        params: [{ name: 'url', description: 'URL to shorten', type: 'string|number' }],
        returnType: 'string',
        returnDescription:
            'The shortened URL when the call happens during a send; in any other context the supplied value unchanged.',
        syntax: 'WrapLongURL(url)',
        example: "%%=WrapLongURL('https://example.com/a/very/long/path')=%%",
    },
];
